/* Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit. */
/** Per subject kind, the read paths it can change (invalidation.json). */
export const RULES: Record<string, string[]> = {
  "mission": [
    "/v1/world/graph**",
    "/v1/missions**",
    "/v1/attention",
    "/v1/digest",
    "/v1/status**"
  ],
  "plan": [
    "/v1/world/graph**",
    "/v1/missions/*/plan",
    "/v1/missions/*/timeline**",
    "/v1/plans/{id}",
    "/v1/missions**"
  ],
  "task": [
    "/v1/world/graph**",
    "/v1/missions/*/plan",
    "/v1/missions/*/timeline**",
    "/v1/tasks/{id}/executions",
    "/v1/digest"
  ],
  "execution": [
    "/v1/world/graph**",
    "/v1/executions/{id}**",
    "/v1/tasks/*/executions",
    "/v1/missions/*/timeline**",
    "/v1/digest"
  ],
  "checkpoint": [
    "/v1/executions/*/checkpoints"
  ],
  "approval": [
    "/v1/world/graph**",
    "/v1/approvals**",
    "/v1/attention",
    "/v1/missions**"
  ],
  "verification": [
    "/v1/world/graph**",
    "/v1/verifications/{id}",
    "/v1/missions/*/verifications",
    "/v1/missions/*/timeline**",
    "/v1/attention",
    "/v1/digest"
  ],
  "review": [
    "/v1/world/graph**",
    "/v1/missions/*/reviews",
    "/v1/missions/*/timeline**",
    "/v1/attention",
    "/v1/digest"
  ],
  "knowledge_item": [
    "/v1/world/graph**",
    "/v1/knowledge**",
    "/v1/attention"
  ],
  "relation": [
    "/v1/world/graph**",
    "/v1/knowledge/**"
  ],
  "feedback": [
    "/v1/knowledge**"
  ],
  "meeting": [
    "/v1/world/graph**",
    "/v1/knowledge**"
  ],
  "decision": [
    "/v1/knowledge**"
  ],
  "project": [
    "/v1/world/graph**",
    "/v1/projects**",
    "/v1/status**",
    "/v1/digest"
  ],
  "repository": [
    "/v1/world/graph**",
    "/v1/projects**",
    "/v1/status**",
    "/v1/repositories/{id}/**",
    "/v1/attention",
    "/v1/digest"
  ],
  "repository_inspection": [
    "/v1/repositories/**",
    "/v1/projects**"
  ],
  "message": [
    "/v1/conversations/**"
  ],
  "idea": [
    "/v1/ideas**"
  ],
  "automation": [
    "/v1/world/graph**",
    "/v1/automations**",
    "/v1/attention"
  ],
  "automation_run": [
    "/v1/world/graph**",
    "/v1/automations**",
    "/v1/automation-runs/{id}"
  ],
  "account": [
    "/v1/accounts",
    "/v1/attention"
  ],
  "resource_policy": [
    "/v1/accounts"
  ],
  "harness": [
    "/v1/harnesses"
  ],
  "route_decision": [
    "/v1/world/graph**",
    "/v1/route-decisions**"
  ],
  "policy_decision": [
    "/v1/world/graph**",
    "/v1/policy-decisions**"
  ],
  "policy_rule": [
    "/v1/policies"
  ],
  "provider_terms": [
    "/v1/provider-terms"
  ],
  "session": [
    "/v1/world/graph**",
    "/v1/sessions**"
  ],
  "context_package": [
    "/v1/world/graph**",
    "/v1/context/{id}"
  ],
  "device": [
    "/v1/devices",
    "/v1/sync"
  ],
  "user": [
    "/v1/digest",
    "/v1/policies"
  ],
  "principal": [
    "/v1/**"
  ],
  "execution_node": [],
  "model": []
};
