/* Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit. */
export const MOTION = {"state": 160, "row": 200, "inspector": 220, "sheet": 280, "pulse": 240, "toast": 160} as const;
export const EASING = "cubic-bezier(.22,.8,.18,1)";
export const BREAKPOINTS = {"tablet": 600, "desktop": 1000} as const;
export const TARGETS = {"desktop": 28, "phone": 44} as const;
