/* GENERATED by tools/gen_cluster_spec.py from claude_sessions/cluster_spec.py.
   Do not edit — the next run overwrites it, and tests/test_cluster_parity.py
   fails while it is stale.

   Every number the cluster and the conduit are made of, so the three renderers
   that draw them cannot drift apart. The reasoning for each one lives in the
   Python module and in notes/cluster-spec.md; only the values are here. */

export const CLUSTER = {
  SHELL_BY_DETAIL: {"0": [12, 30], "1": [42, 120], "2": [162, 480]},
  SHELL_ROD_HALF: 0.013,
  SPOKE_HALF: 0.04,
  WEB_ROD_HALF: 0.009,
  WEB_R: 0.53,
  MOTE_R: 0.61,
  ORBIT_R: 0.47,
  SPOKE_IN: 0.22,
  SPOKE_OUT: 0.9,
  SPOKE_FADE: 0.34,
  CORE_R: 0.16,
  SEED_R: 0.0645,
  FRAME_HALF: 0.042,
  FRAME_EDGES: 30,
  FRAME_NODES: 12,
  FRAME_BEAD_R: 0.135,
  SHELL_BEAD_R: 0.0375,
  CORE_SHELL_R: 0.26,
  MOTE_MIN: 12,
  MOTE_MAX: 240,
  ORBIT_N: 28,
  ROD_ALPHA_BY_EDGES: {"30": 1.0, "120": 0.42, "480": 0.16},
  LOD_BREAKS: [0.22, 0.7],
  CONDUIT_HOUSING: 1.08,
  CONDUIT_GLASS: 0.82,
  CONDUIT_CORE: 0.44,
  CONDUIT_RAIL: 0.14,
  CONDUIT_RAIL_OFFSET: 0.86,
  COLLAR_D: 1.49,
  COLLAR_THICK: 0.17,
  RAIL_NODE: 0.18,
  FILAMENT_GOLD: 0.08,
  FILAMENT_CROSS: 0.1,
  CONDUIT_PARTICLE: 0.11,
  CONDUIT_REACH: 0.86,
  CONDUIT_CLAMP: 0.45,
  HUB_HOUSING: 2.44,
  HUB_GLASS: 2.0,
  HUB_ENERGY: 1.1,
  HUB_HOT: 0.56,
  HUB_RING_OUTER: 2.65,
  HUB_RING_INNER: 2.35,
  HUB_RING_ENERGY: 1.94,
  ROLE_UNIFORMS: ["u_acc", "u_acc2", "u_err", "u_warn", "u_ok", "u_white"],
  PALETTE_FAMILIES: [[8, "violet", [1, 2, 0, 3]], [3, "blend", [1, 0, 2, 5]], [2, "cyan", [0, 1, 4, 3]], [2, "magenta", [2, 1, 0, 3]], [3, "gold", [3, 2, 1, 0]], [2, "green", [4, 0, 1, 3]]],
  SHELL_SPLIT: 0.75,
  WEB_SPLIT: 0.667,
  MOTE_GOLD: 0.09,
  MOTE_WHITE: 0.015,
  FILAMENT_MIX: [0.6, 0.85, 0.95],
} as const;

export type ClusterSpec = typeof CLUSTER;
