/* GENERATED by tools/gen_tour.py from claude_sessions/tour.py.
   Do not edit — the next run overwrites it, and tests/test_tour.py fails while
   it is stale.

   The guided tour, which the desktop app runs as an overlay and the terminal UI
   prints as a screen. The website cannot import the Python, so it gets this;
   the reasoning for every step lives in the module, and only the words are
   here. */

export type TourStep = {
  id: string;
  title: string;
  body: string;
  /** GUI page id this step is about, or '' */
  page: string;
  /** project tab id, or '' */
  tab: string;
  /** the terminal UI key that reaches the same thing, or '' */
  key: string;
  /** manual page, without the extension, or '' */
  docs: string;
  /** the manual URL, or '' */
  docsUrl: string;
};

export const TOUR_SHORT: TourStep[] = [
  {
    "id": "what",
    "title": "What archeus is",
    "body": "archeus is the workspace layer around your coding CLI. Your projects stop being a stream of chats and become workspaces that remember: per-project memory, every session you have ever had, and control over what the next one costs. It drives Claude Code, OpenAI Codex and pi, and it never replaces them \u2014 it launches the real binary.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "index",
    "docsUrl": "https://claudectl.space/docs/index/"
  },
  {
    "id": "dashboard",
    "title": "The dashboard",
    "body": "One screen for the state of everything: quota and burn as gauges, what is running right now, your projects by recent spend, and the session you were last in. Start here when you sit down \u2014 the Continue tile usually knows what you want before you do.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://claudectl.space/docs/dashboard/"
  },
  {
    "id": "projects",
    "title": "Open a project",
    "body": "A project is a directory archeus has seen a session in. Picking one opens its own set of tabs \u2014 its sessions, its memory, its CLAUDE.md, its spend. Nothing is configured to make a directory a project; run a session in it once and it is one.",
    "page": "home",
    "tab": "",
    "key": "Enter",
    "docs": "projects",
    "docsUrl": "https://claudectl.space/docs/projects/"
  },
  {
    "id": "sessions",
    "title": "Every session you have had",
    "body": "Resume, rename, archive or export any conversation in the project, across every account. This is the reason archeus exists: a transcript you cannot find is a transcript you paid for twice.",
    "page": "",
    "tab": "sessions",
    "key": "s",
    "docs": "sessions",
    "docsUrl": "https://claudectl.space/docs/sessions/"
  },
  {
    "id": "memory",
    "title": "Memory that survives the session",
    "body": "archeus builds a semantic graph of the project \u2014 its modules, its services, the lessons it has learned \u2014 and injects the task-relevant part into every new session. Build it once from the Memory tab and it keeps itself current on a schedule.",
    "page": "",
    "tab": "memory",
    "key": "m",
    "docs": "memory",
    "docsUrl": "https://claudectl.space/docs/memory/"
  },
  {
    "id": "launch",
    "title": "Decide what a session costs",
    "body": "Model, effort, permission mode, thinking budget and which account it runs under are all decided before the window opens. The same choices can be pinned per project, so the expensive project and the cheap one do not get the same defaults by accident.",
    "page": "settings",
    "tab": "",
    "key": "n",
    "docs": "configuration",
    "docsUrl": "https://claudectl.space/docs/configuration/"
  },
  {
    "id": "go",
    "title": "Launch one",
    "body": "Pick a project and start a session. archeus opens the unmodified CLI in its own window with your choices applied, the memory digest injected and the status line reporting context, spend and quota as you work.",
    "page": "home",
    "tab": "",
    "key": "n",
    "docs": "quickstart",
    "docsUrl": "https://claudectl.space/docs/quickstart/"
  }
];

export const TOUR_LONG: TourStep[] = [
  {
    "id": "long-what",
    "title": "What archeus is",
    "body": "The memory and workspace layer for AI coding agents. It sits beside Claude Code, Codex and pi rather than in front of them \u2014 it launches the real binary with your settings, reads what those tools record, and adds the three things none of them keep: memory per project, a history you can search, and a budget you can see.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "index",
    "docsUrl": "https://claudectl.space/docs/index/"
  },
  {
    "id": "long-dashboard",
    "title": "Dashboard",
    "body": "Quota, today's burn, tooling health and live activity as four gauges, over the sessions running right now, your projects and the one to continue. Use it as the answer to \"where was I\" and \"what is this costing me\" without opening anything.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://claudectl.space/docs/dashboard/"
  },
  {
    "id": "long-live",
    "title": "Live sessions",
    "body": "Every session being worked in at this moment, one row each: the project, who is on it, what tool call it is blocked on this second, and the shape of its recent activity as coloured ticks. For watching several agents at once \u2014 click a row for the full flow graph.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://claudectl.space/docs/dashboard/"
  },
  {
    "id": "long-sessions",
    "title": "Sessions",
    "body": "Every conversation in this project, across every account: resume it, fork it, rename it, archive it, export it to Markdown, or replay it as a flow graph. Use rename early \u2014 a session called \"continue\" is a session you will never find again.",
    "page": "",
    "tab": "sessions",
    "key": "s",
    "docs": "sessions",
    "docsUrl": "https://claudectl.space/docs/sessions/"
  },
  {
    "id": "long-flow",
    "title": "Flow graph",
    "body": "A session replayed on its own clock: prompts, model turns, tool calls, results, errors and subagent lanes, with play, scrub and zoom. Idle gaps are clamped, so a twelve-hour session plays in seconds. Use it to see where a run actually spent its time.",
    "page": "",
    "tab": "sessions",
    "key": "",
    "docs": "sessions",
    "docsUrl": "https://claudectl.space/docs/sessions/"
  },
  {
    "id": "long-memory",
    "title": "Memory",
    "body": "A semantic graph of the project \u2014 entities, relations and lessons \u2014 built by Claude and injected into every new session as a compact digest, with `archeus recall \"<topic>\"` for the detail. It is what stops every session starting by re-reading the same eight files.",
    "page": "",
    "tab": "memory",
    "key": "m",
    "docs": "memory",
    "docsUrl": "https://claudectl.space/docs/memory/"
  },
  {
    "id": "long-lessons",
    "title": "Lessons",
    "body": "What went wrong and what fixed it, mined out of your own transcripts and held for review before anything is written. Approve one and it joins the memory graph, so the next session in that project starts already knowing it.",
    "page": "",
    "tab": "memory",
    "key": "",
    "docs": "memory",
    "docsUrl": "https://claudectl.space/docs/memory/"
  },
  {
    "id": "long-claudemd",
    "title": "CLAUDE.md",
    "body": "The instruction file block by block, what each block costs in tokens, which blocks archeus maintains, and every version it has replaced. Use it when the file has grown past the point where anyone reads it \u2014 the cost column is the argument.",
    "page": "",
    "tab": "claudemd",
    "key": "",
    "docs": "memory",
    "docsUrl": "https://claudectl.space/docs/memory/"
  },
  {
    "id": "long-audit",
    "title": "Context audit",
    "body": "What ONE turn costs across every surface at once: this project's CLAUDE.md, your global one, the memory digest, the hooks, the MCP tool definitions. Run it before you wonder why a short question cost so much.",
    "page": "",
    "tab": "audit",
    "key": "",
    "docs": "usage",
    "docsUrl": "https://claudectl.space/docs/usage/"
  },
  {
    "id": "long-review",
    "title": "Review",
    "body": "A code review over the working tree, the staged changes or a branch, run by Claude with the project's own memory in scope. For the pass you want before a commit, not instead of one.",
    "page": "",
    "tab": "review",
    "key": "",
    "docs": "plan-execute",
    "docsUrl": "https://claudectl.space/docs/plan-execute/"
  },
  {
    "id": "long-planexec",
    "title": "Plan \u2192 Execute",
    "body": "One model writes a plan, you approve or edit it, another executes it step by step with a gate between. For work too big for one turn, where the expensive mistake is the plan rather than the code.",
    "page": "",
    "tab": "planexec",
    "key": "",
    "docs": "plan-execute",
    "docsUrl": "https://claudectl.space/docs/plan-execute/"
  },
  {
    "id": "long-pusage",
    "title": "This project's spend",
    "body": "The same token history as the account-wide page, narrowed to one project and one timeline. It is the number to bring to the question nobody can answer from a monthly total \u2014 whether the work this repository needs is worth what it costs to do it here.",
    "page": "",
    "tab": "pusage",
    "key": "",
    "docs": "usage",
    "docsUrl": "https://claudectl.space/docs/usage/"
  },
  {
    "id": "long-repos",
    "title": "Repos",
    "body": "Every git repo, submodule and linked worktree under the project, with branch, dirty count and ahead/behind, read from `.git` without spawning git. For a workspace that is a parent of repositories rather than a repository.",
    "page": "",
    "tab": "worktrees",
    "key": "",
    "docs": "projects",
    "docsUrl": "https://claudectl.space/docs/projects/"
  },
  {
    "id": "long-tools",
    "title": "Tools",
    "body": "The architecture graph of the project as an interactive cluster, Claude Code's own record of it, and the loop file. The graph is worth opening once per project: it is the shape of the codebase as archeus understands it, which is also what it injects.",
    "page": "",
    "tab": "tools",
    "key": "",
    "docs": "architecture",
    "docsUrl": "https://claudectl.space/docs/architecture/"
  },
  {
    "id": "long-globalmd",
    "title": "Global CLAUDE.md",
    "body": "The instructions read in every session on an account, with the conventions archeus has noticed in your projects offered for promotion into it. For the rules that are about YOU rather than about one codebase.",
    "page": "globalmd",
    "tab": "",
    "key": "g",
    "docs": "memory",
    "docsUrl": "https://claudectl.space/docs/memory/"
  },
  {
    "id": "long-agents",
    "title": "Agents",
    "body": "Subagent definitions \u2014 browse the library, write one by hand, or have Claude draft one from a description. A good subagent is a specialist you delegate to; the description field is what decides whether it is ever picked.",
    "page": "agents",
    "tab": "",
    "key": "a",
    "docs": "agents",
    "docsUrl": "https://claudectl.space/docs/agents/"
  },
  {
    "id": "long-skills",
    "title": "Skills",
    "body": "SKILL.md skills: the bundled starters, your own library and the ones installed in a project. A skill is a procedure you want followed the same way every time \u2014 a release runbook, a review checklist.",
    "page": "skills",
    "tab": "",
    "key": "",
    "docs": "agent-library",
    "docsUrl": "https://claudectl.space/docs/agent-library/"
  },
  {
    "id": "long-hooks",
    "title": "Hooks",
    "body": "Claude Code hooks per account, from a template or your own: block a command, format on write, inject context at session start. archeus installs its own three here too, and can repair them when a path moves.",
    "page": "hooks",
    "tab": "",
    "key": "h",
    "docs": "hooks",
    "docsUrl": "https://claudectl.space/docs/hooks/"
  },
  {
    "id": "long-mcp",
    "title": "MCP servers",
    "body": "Every MCP server configured, its status, and the tool documentation it can write into your global CLAUDE.md. Worth auditing: an MCP server you forgot about is tool definitions in every single turn.",
    "page": "mcp",
    "tab": "",
    "key": "c",
    "docs": "mcp",
    "docsUrl": "https://claudectl.space/docs/mcp/"
  },
  {
    "id": "long-plugins",
    "title": "Plugins",
    "body": "The marketplaces you have registered and every plugin installed from them, with what each one contributes. Every install goes through a review gate first \u2014 a plugin is code that runs in your sessions.",
    "page": "plugins",
    "tab": "",
    "key": "",
    "docs": "plugin",
    "docsUrl": "https://claudectl.space/docs/plugin/"
  },
  {
    "id": "long-ostyles",
    "title": "Output styles",
    "body": "The output styles Claude Code can wear, and which is active. A style changes how answers are written, not what the model is; it is the cheapest way to stop fighting the tone.",
    "page": "ostyles",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://claudectl.space/docs/configuration/"
  },
  {
    "id": "long-usage",
    "title": "Usage & cost",
    "body": "Token spend and rate limits across every account, by day, by project and by model, with the plan windows as they actually stand. The question it answers is which project is expensive, which is rarely the one you would guess.",
    "page": "usage",
    "tab": "",
    "key": "u",
    "docs": "usage",
    "docsUrl": "https://claudectl.space/docs/usage/"
  },
  {
    "id": "long-accounts",
    "title": "Accounts",
    "body": "Every login, each with its own config directory, credentials, quota, hooks and plugins. Add a second one and a full 5-hour window stops being the end of the afternoon.",
    "page": "accounts",
    "tab": "",
    "key": "",
    "docs": "accounts",
    "docsUrl": "https://claudectl.space/docs/accounts/"
  },
  {
    "id": "long-rotation",
    "title": "Account rotation",
    "body": "When the account in use fills its window, the next one with headroom takes over \u2014 new work by itself, and a session you are sitting in either offered the move or moved for you. The status line warns before the window is spent; a hook catches it if you are already stuck.",
    "page": "accounts",
    "tab": "",
    "key": "",
    "docs": "accounts",
    "docsUrl": "https://claudectl.space/docs/accounts/"
  },
  {
    "id": "long-models",
    "title": "Models & providers",
    "body": "The backends a session can run against \u2014 Anthropic, a local server, OpenRouter or OmniRoute \u2014 each with its own model and failover list. For routing the cheap work somewhere cheap without changing how you work.",
    "page": "models",
    "tab": "",
    "key": "",
    "docs": "providers",
    "docsUrl": "https://claudectl.space/docs/providers/"
  },
  {
    "id": "long-loops",
    "title": "Loops",
    "body": "Start a `/loop` in its own session, watch it fire on its schedule, and end it. For the recurring job that does not need you: a nightly review, a metrics refresh.",
    "page": "loops",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://claudectl.space/docs/configuration/"
  },
  {
    "id": "long-statusline",
    "title": "Status line",
    "body": "Model, account, git state, context pressure, memory age, spend and both plan windows, on two lines under your prompt, on every turn. It is the one surface that tells you a session is going wrong while there is still time to do something.",
    "page": "updates",
    "tab": "",
    "key": "",
    "docs": "statusline",
    "docsUrl": "https://claudectl.space/docs/statusline/"
  },
  {
    "id": "long-harness",
    "title": "Harnesses",
    "body": "Every coding CLI archeus drives \u2014 whether it is installed, how it is configured, and the screens only it has. One project list, one memory graph, three CLIs: a Codex session and a Claude session in the same directory are the same workspace.",
    "page": "harness",
    "tab": "",
    "key": "",
    "docs": "harnesses",
    "docsUrl": "https://claudectl.space/docs/harnesses/"
  },
  {
    "id": "long-client",
    "title": "Claude Code's own record",
    "body": "What the CLI keeps about itself: versions, how much disk its transcripts and caches have taken, the background agents it is running, and its own settings. Read-only, and the first place to look when the tool disagrees with what you think you configured.",
    "page": "client",
    "tab": "",
    "key": "",
    "docs": "troubleshooting",
    "docsUrl": "https://claudectl.space/docs/troubleshooting/"
  },
  {
    "id": "long-handoff",
    "title": "Context hand-off",
    "body": "When the context window fills, hand the conversation to a fresh session \u2014 optionally under another account \u2014 seeded with what it needs rather than with the whole transcript. The successor starts clear instead of starting where the last one ran out of room.",
    "page": "home",
    "tab": "",
    "key": "K",
    "docs": "context-handoff",
    "docsUrl": "https://claudectl.space/docs/context-handoff/"
  },
  {
    "id": "long-search",
    "title": "Search",
    "body": "Full-text search across every transcript on the machine, every account and every CLI. For \"I solved this three weeks ago and I cannot remember where\".",
    "page": "searchp",
    "tab": "",
    "key": "",
    "docs": "sessions",
    "docsUrl": "https://claudectl.space/docs/sessions/"
  },
  {
    "id": "long-logs",
    "title": "Logs",
    "body": "What archeus itself did and why it failed \u2014 its own Claude calls, background jobs, the scheduler, the proxy. The first place to look when something did not happen, which is harder to notice than something that broke.",
    "page": "logs",
    "tab": "",
    "key": "",
    "docs": "troubleshooting",
    "docsUrl": "https://claudectl.space/docs/troubleshooting/"
  },
  {
    "id": "long-paths",
    "title": "Paths & limits",
    "body": "Where archeus finds your editor and your CLIs, what its own Claude calls may spend, and how large the memory graph may grow. The spend cap is the one to set on day one.",
    "page": "paths",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://claudectl.space/docs/configuration/"
  },
  {
    "id": "long-appearance",
    "title": "Appearance",
    "body": "Thirty-two palettes, eight skins and four worlds \u2014 a palette answers \"what colours\", a skin answers \"what is this application\". Motion and the background scene both have an off switch, and both honour `prefers-reduced-motion`.",
    "page": "appearance",
    "tab": "",
    "key": "",
    "docs": "desktop",
    "docsUrl": "https://claudectl.space/docs/desktop/"
  },
  {
    "id": "long-updates",
    "title": "Updates & schedules",
    "body": "Versions of archeus, of your CLIs and of the model catalogue, plus what archeus does on its own: update checks, notifications and the auto-memory schedule. Auto-memory is the setting that makes memory something you stop thinking about.",
    "page": "updates",
    "tab": "",
    "key": "",
    "docs": "installation",
    "docsUrl": "https://claudectl.space/docs/installation/"
  },
  {
    "id": "long-tui",
    "title": "The terminal UI",
    "body": "Everything here exists in the terminal too \u2014 `archeus` with no arguments \u2014 and the two are kept in parity by a test rather than by intention. Press `?` there for every key.",
    "page": "helpp",
    "tab": "",
    "key": "?",
    "docs": "tui",
    "docsUrl": "https://claudectl.space/docs/tui/"
  },
  {
    "id": "long-plugin",
    "title": "The plugin",
    "body": "archeus also installs as a Claude Code plugin, so a session can reach its own project's memory and history without leaving the terminal. It ships no hooks on purpose \u2014 the hook manager already owns those, and one settings entry with two owners is a bug waiting to happen.",
    "page": "plugins",
    "tab": "",
    "key": "",
    "docs": "plugin",
    "docsUrl": "https://claudectl.space/docs/plugin/"
  }
];

export const DOCS_BASE = "https://claudectl.space/docs";
