/* GENERATED by tools/gen_tour.py from claude_sessions/tour.py.
   Do not edit — the next run overwrites it, and tests/test_tour.py fails while
   it is stale.

   The guided tour, which the desktop app runs as an overlay and the terminal UI
   prints as a screen. The website cannot import the Python, so it gets this;
   the reasoning for every step lives in the module, and only the words are
   here. */

export type TourStep = {
  id: string;
  title: string;
  body: string;
  /** GUI page id this step is about, or '' */
  page: string;
  /** project tab id, or '' */
  tab: string;
  /** the terminal UI key that reaches the same thing, or '' */
  key: string;
  /** manual page, without the extension, or '' */
  docs: string;
  /** the manual URL, or '' */
  docsUrl: string;
};

export const TOUR_SHORT: TourStep[] = [
  {
    "id": "what",
    "title": "What archeus is",
    "body": "The workspace layer around your coding CLI: per-project memory, every session you have had, and control over what the next one costs.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "index",
    "docsUrl": "https://docs.claudectl.space/index/"
  },
  {
    "id": "dashboard",
    "title": "The dashboard",
    "body": "One screen for quota, today's burn, what is running now, and the session to continue.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://docs.claudectl.space/dashboard/"
  },
  {
    "id": "projects",
    "title": "Open a project",
    "body": "A directory archeus has seen a session in, opened as its own workspace of tabs.",
    "page": "home",
    "tab": "",
    "key": "Enter",
    "docs": "projects",
    "docsUrl": "https://docs.claudectl.space/projects/"
  },
  {
    "id": "sessions",
    "title": "Every session you have had",
    "body": "Resume, rename, archive or export any conversation in this project, across every account.",
    "page": "",
    "tab": "sessions",
    "key": "s",
    "docs": "sessions",
    "docsUrl": "https://docs.claudectl.space/sessions/"
  },
  {
    "id": "memory",
    "title": "Memory that survives the session",
    "body": "A graph of the project that archeus injects into every new session and refreshes on a schedule.",
    "page": "",
    "tab": "memory",
    "key": "m",
    "docs": "memory",
    "docsUrl": "https://docs.claudectl.space/memory/"
  },
  {
    "id": "launch",
    "title": "Decide what a session costs",
    "body": "Model, effort, permission mode and account are all decided before the window opens, and can be pinned per project.",
    "page": "settings",
    "tab": "",
    "key": "n",
    "docs": "configuration",
    "docsUrl": "https://docs.claudectl.space/configuration/"
  },
  {
    "id": "go",
    "title": "Launch one",
    "body": "archeus opens the real CLI with your choices applied, the memory digest injected and the status line running.",
    "page": "home",
    "tab": "",
    "key": "n",
    "docs": "quickstart",
    "docsUrl": "https://docs.claudectl.space/quickstart/"
  }
];

export const TOUR_LONG: TourStep[] = [
  {
    "id": "long-what",
    "title": "What archeus is",
    "body": "The memory and workspace layer beside Claude Code, Codex and pi: it launches the real binary, never replaces it.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "index",
    "docsUrl": "https://docs.claudectl.space/index/"
  },
  {
    "id": "long-dashboard",
    "title": "Dashboard",
    "body": "Quota, burn, tooling health and live activity as four gauges, over your projects and the session to continue.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://docs.claudectl.space/dashboard/"
  },
  {
    "id": "long-live",
    "title": "Live sessions",
    "body": "Every session being worked in right now, one row each, showing what tool call it is blocked on.",
    "page": "home",
    "tab": "",
    "key": "",
    "docs": "dashboard",
    "docsUrl": "https://docs.claudectl.space/dashboard/"
  },
  {
    "id": "long-sessions",
    "title": "Sessions",
    "body": "Every conversation in this project, across every account: resume, fork, rename, archive, export or replay it.",
    "page": "",
    "tab": "sessions",
    "key": "s",
    "docs": "sessions",
    "docsUrl": "https://docs.claudectl.space/sessions/"
  },
  {
    "id": "long-flow",
    "title": "Flow graph",
    "body": "A session replayed on its own clock with idle gaps clamped, so a twelve-hour run plays in seconds.",
    "page": "",
    "tab": "sessions",
    "key": "",
    "docs": "sessions",
    "docsUrl": "https://docs.claudectl.space/sessions/"
  },
  {
    "id": "long-memory",
    "title": "Memory",
    "body": "A graph of the project's entities, relations and lessons, injected into every new session as a compact digest.",
    "page": "",
    "tab": "memory",
    "key": "m",
    "docs": "memory",
    "docsUrl": "https://docs.claudectl.space/memory/"
  },
  {
    "id": "long-lessons",
    "title": "Lessons",
    "body": "What went wrong and what fixed it, mined from your transcripts and held for review before anything is written.",
    "page": "",
    "tab": "memory",
    "key": "",
    "docs": "memory",
    "docsUrl": "https://docs.claudectl.space/memory/"
  },
  {
    "id": "long-claudemd",
    "title": "CLAUDE.md",
    "body": "The instruction file block by block, what each block costs, and an editor for the half you wrote.",
    "page": "",
    "tab": "claudemd",
    "key": "",
    "docs": "memory",
    "docsUrl": "https://docs.claudectl.space/memory/"
  },
  {
    "id": "long-audit",
    "title": "Context audit",
    "body": "What one turn costs across every surface at once, plus this project's health and what the CLI records.",
    "page": "",
    "tab": "audit",
    "key": "",
    "docs": "usage",
    "docsUrl": "https://docs.claudectl.space/usage/"
  },
  {
    "id": "long-review",
    "title": "Code Review",
    "body": "A code review over the working tree, staged changes or a branch, with the project's memory in scope.",
    "page": "",
    "tab": "review",
    "key": "",
    "docs": "plan-execute",
    "docsUrl": "https://docs.claudectl.space/plan-execute/"
  },
  {
    "id": "long-planexec",
    "title": "Plan \u2192 Execute",
    "body": "One model writes a plan you approve or edit, another executes it step by step with a gate between.",
    "page": "",
    "tab": "planexec",
    "key": "",
    "docs": "plan-execute",
    "docsUrl": "https://docs.claudectl.space/plan-execute/"
  },
  {
    "id": "long-pusage",
    "title": "This project's spend",
    "body": "The same token history as the account-wide page, narrowed to one project and one timeline.",
    "page": "",
    "tab": "pusage",
    "key": "",
    "docs": "usage",
    "docsUrl": "https://docs.claudectl.space/usage/"
  },
  {
    "id": "long-repos",
    "title": "Repos",
    "body": "Every git repo, submodule and linked worktree under the project, with branch and dirty count, read without spawning git.",
    "page": "",
    "tab": "worktrees",
    "key": "",
    "docs": "projects",
    "docsUrl": "https://docs.claudectl.space/projects/"
  },
  {
    "id": "long-tools",
    "title": "Tools",
    "body": "What this project launches with \u2014 its agents, directories and PATH \u2014 beside the commands it has actually run.",
    "page": "",
    "tab": "tools",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://docs.claudectl.space/configuration/"
  },
  {
    "id": "long-globalmd",
    "title": "Global CLAUDE.md",
    "body": "The instructions read in every session on an account, with conventions from your projects offered for promotion into it.",
    "page": "globalmd",
    "tab": "",
    "key": "g",
    "docs": "memory",
    "docsUrl": "https://docs.claudectl.space/memory/"
  },
  {
    "id": "long-agents",
    "title": "Agents",
    "body": "Subagent definitions you browse, write by hand or have Claude draft; the description decides whether one is ever picked.",
    "page": "agents",
    "tab": "",
    "key": "a",
    "docs": "agents",
    "docsUrl": "https://docs.claudectl.space/agents/"
  },
  {
    "id": "long-skills",
    "title": "Skills",
    "body": "A procedure you want followed the same way every time: a release runbook, a review checklist, a house style.",
    "page": "skills",
    "tab": "",
    "key": "",
    "docs": "agent-library",
    "docsUrl": "https://docs.claudectl.space/agent-library/"
  },
  {
    "id": "long-hooks",
    "title": "Hooks",
    "body": "Claude Code hooks per account: block a command, format on write, inject context when a session starts.",
    "page": "hooks",
    "tab": "",
    "key": "h",
    "docs": "hooks",
    "docsUrl": "https://docs.claudectl.space/hooks/"
  },
  {
    "id": "long-mcp",
    "title": "MCP servers",
    "body": "Every MCP server configured and its status; one you forgot about is tool definitions in every single turn.",
    "page": "mcp",
    "tab": "",
    "key": "c",
    "docs": "mcp",
    "docsUrl": "https://docs.claudectl.space/mcp/"
  },
  {
    "id": "long-plugins",
    "title": "Plugins",
    "body": "The marketplaces you registered and every plugin installed from them, each through a review gate before it runs.",
    "page": "plugins",
    "tab": "",
    "key": "",
    "docs": "plugin",
    "docsUrl": "https://docs.claudectl.space/plugin/"
  },
  {
    "id": "long-ostyles",
    "title": "Output styles",
    "body": "Output styles change how answers are written, not which model writes them, and it is the cheapest tone fix.",
    "page": "ostyles",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://docs.claudectl.space/configuration/"
  },
  {
    "id": "long-usage",
    "title": "Usage & cost",
    "body": "Token spend and rate limits across every account, by day, project and model, with the plan windows as they stand.",
    "page": "usage",
    "tab": "",
    "key": "u",
    "docs": "usage",
    "docsUrl": "https://docs.claudectl.space/usage/"
  },
  {
    "id": "long-accounts",
    "title": "Accounts",
    "body": "Every login with its own config directory, credentials, quota, hooks and plugins, switchable per launch.",
    "page": "accounts",
    "tab": "",
    "key": "",
    "docs": "accounts",
    "docsUrl": "https://docs.claudectl.space/accounts/"
  },
  {
    "id": "long-rotation",
    "title": "Account rotation",
    "body": "When the account in use fills its window, the next one with headroom takes over instead of stopping you.",
    "page": "accounts",
    "tab": "",
    "key": "",
    "docs": "accounts",
    "docsUrl": "https://docs.claudectl.space/accounts/"
  },
  {
    "id": "long-models",
    "title": "Models & providers",
    "body": "The backends a session can run against \u2014 Anthropic, a local server, OpenRouter or OmniRoute \u2014 each with its own failover list.",
    "page": "models",
    "tab": "",
    "key": "",
    "docs": "providers",
    "docsUrl": "https://docs.claudectl.space/providers/"
  },
  {
    "id": "long-loops",
    "title": "Loops",
    "body": "Start a recurring job in its own session, watch it fire on schedule, and end it when you are done.",
    "page": "loops",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://docs.claudectl.space/configuration/"
  },
  {
    "id": "long-statusline",
    "title": "Status line",
    "body": "Model, account, git state, context pressure, memory age and both plan windows, under your prompt on every turn.",
    "page": "updates",
    "tab": "",
    "key": "",
    "docs": "statusline",
    "docsUrl": "https://docs.claudectl.space/statusline/"
  },
  {
    "id": "long-harness",
    "title": "Harnesses",
    "body": "One project list and one memory graph across three CLIs, so a Codex and a Claude session share a workspace.",
    "page": "harness",
    "tab": "",
    "key": "",
    "docs": "harnesses",
    "docsUrl": "https://docs.claudectl.space/harnesses/"
  },
  {
    "id": "long-client",
    "title": "Claude Code's own record",
    "body": "What the CLI keeps about itself: versions, disk used, background agents and its own settings, all read-only.",
    "page": "client",
    "tab": "",
    "key": "",
    "docs": "troubleshooting",
    "docsUrl": "https://docs.claudectl.space/troubleshooting/"
  },
  {
    "id": "long-handoff",
    "title": "Context hand-off",
    "body": "Hand a full conversation to a fresh session, optionally under another account, seeded with what it needs.",
    "page": "home",
    "tab": "",
    "key": "K",
    "docs": "context-handoff",
    "docsUrl": "https://docs.claudectl.space/context-handoff/"
  },
  {
    "id": "long-search",
    "title": "Search",
    "body": "Full-text search across every transcript on the machine, every account and every CLI.",
    "page": "searchp",
    "tab": "",
    "key": "",
    "docs": "sessions",
    "docsUrl": "https://docs.claudectl.space/sessions/"
  },
  {
    "id": "long-logs",
    "title": "Logs",
    "body": "What archeus itself did and why it failed: its own Claude calls, background jobs, the scheduler and the proxy.",
    "page": "logs",
    "tab": "",
    "key": "",
    "docs": "troubleshooting",
    "docsUrl": "https://docs.claudectl.space/troubleshooting/"
  },
  {
    "id": "long-paths",
    "title": "Paths & limits",
    "body": "Where archeus finds your editor and CLIs, what its own Claude calls may spend, and how large memory may grow.",
    "page": "paths",
    "tab": "",
    "key": "",
    "docs": "configuration",
    "docsUrl": "https://docs.claudectl.space/configuration/"
  },
  {
    "id": "long-appearance",
    "title": "Appearance",
    "body": "Thirty-two palettes, eight skins and four worlds, with an off switch for motion and for the background scene.",
    "page": "appearance",
    "tab": "",
    "key": "",
    "docs": "desktop",
    "docsUrl": "https://docs.claudectl.space/desktop/"
  },
  {
    "id": "long-updates",
    "title": "Updates & schedules",
    "body": "Versions of archeus, your CLIs and the model catalogue, plus the update checks and auto-memory schedule it runs alone.",
    "page": "updates",
    "tab": "",
    "key": "",
    "docs": "installation",
    "docsUrl": "https://docs.claudectl.space/installation/"
  },
  {
    "id": "long-tui",
    "title": "The terminal UI",
    "body": "Everything here exists in the terminal too, kept in parity by a test rather than by intention.",
    "page": "helpp",
    "tab": "",
    "key": "?",
    "docs": "tui",
    "docsUrl": "https://docs.claudectl.space/tui/"
  },
  {
    "id": "long-plugin",
    "title": "The plugin",
    "body": "archeus installs as a Claude Code plugin as well, so a session can reach its own project's memory and history.",
    "page": "plugins",
    "tab": "",
    "key": "",
    "docs": "plugin",
    "docsUrl": "https://docs.claudectl.space/plugin/"
  }
];

export const DOCS_BASE = "https://docs.claudectl.space";
