/* Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit. */
export interface Destination {
  id: 'now' | 'work' | 'world' | 'attention' | 'control';
  label: string;
  /** keyboard shortcut with Ctrl (Windows/Linux) or Cmd (macOS) */
  key: string;
  /** the TUI key (p17-design-gate §3) */
  tui: string;
  /** on a phone: a bottom tab, or the header menu */
  phone: 'tab' | 'menu';
  blurb: string;
}

export const DESTINATIONS: Destination[] = [
  {
    "id": "now",
    "label": "Now",
    "key": "1",
    "tui": "1",
    "phone": "tab",
    "blurb": "What changed, what is happening, and the conversation"
  },
  {
    "id": "work",
    "label": "Work",
    "key": "2",
    "tui": "2",
    "phone": "tab",
    "blurb": "Every mission, grouped by what it waits on"
  },
  {
    "id": "world",
    "label": "World",
    "key": "3",
    "tui": "3",
    "phone": "tab",
    "blurb": "Projects, repositories and what Archeus knows"
  },
  {
    "id": "attention",
    "label": "Attention",
    "key": "j",
    "tui": "a",
    "phone": "tab",
    "blurb": "Everything that waits on you"
  },
  {
    "id": "control",
    "label": "Control",
    "key": ",",
    "tui": "4",
    "phone": "menu",
    "blurb": "Autonomy, automations, resources, sessions and clients"
  }
];

export const CONTROL_SECTIONS = [
  {
    "id": "autonomy",
    "label": "Autonomy"
  },
  {
    "id": "automations",
    "label": "Automations"
  },
  {
    "id": "resources",
    "label": "Resources"
  },
  {
    "id": "sessions",
    "label": "Sessions"
  },
  {
    "id": "devices",
    "label": "Clients"
  },
  {
    "id": "about",
    "label": "About"
  }
] as const;

/** The inspector tabs per object kind, in their fixed order (§6.1). */
export const INSPECTOR_TABS: Record<string, string[]> = {
  "mission": [
    "outcome",
    "plan",
    "now",
    "evidence",
    "why",
    "timeline",
    "relations"
  ],
  "execution": [
    "output",
    "checkpoints",
    "relations"
  ],
  "session": [
    "brief",
    "lineage",
    "relations"
  ],
  "knowledge_item": [
    "detail",
    "relations"
  ],
  "automation_run": [
    "explanation",
    "relations"
  ],
  "approval": [
    "detail"
  ],
  "plan": [
    "detail",
    "relations"
  ],
  "verification": [
    "detail",
    "relations"
  ],
  "route_decision": [
    "detail"
  ],
  "policy_decision": [
    "detail"
  ],
  "context_package": [
    "detail"
  ],
  "project": [
    "detail"
  ],
  "repository": [
    "detail"
  ]
};

export const TAB_LABEL: Record<string, string> = {
  "outcome": "Outcome",
  "plan": "Plan",
  "now": "Now",
  "evidence": "Evidence",
  "why": "Why",
  "timeline": "Timeline",
  "relations": "Relations",
  "output": "Output",
  "checkpoints": "Checkpoints",
  "brief": "Brief",
  "lineage": "Lineage",
  "detail": "Detail",
  "explanation": "Explanation"
};
