"""Regenerate the website's copy of `claude_sessions/tour.py`.

Three surfaces run the same guided tour — the GUI overlay, the terminal UI
screen and the apex's Getting started page. Two of them can import the Python;
the website is a Next.js build that cannot, so it gets a generated copy and
`tests/test_tour.py` fails while it is stale.

    py -3 tools/gen_tour.py            # rewrite www/lib/tour.ts
    py -3 tools/gen_tour.py --check    # exit 1 if it is out of date

Same shape, and the same reason, as `tools/gen_cluster_spec.py`.
"""

import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from claude_sessions import tour as T          # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'www', 'lib', 'tour.ts')

BANNER = """/* GENERATED by tools/gen_tour.py from claude_sessions/tour.py.
   Do not edit — the next run overwrites it, and tests/test_tour.py fails while
   it is stale.

   The guided tour, which the desktop app runs as an overlay and the terminal UI
   prints as a screen. The website cannot import the Python, so it gets this;
   the reasoning for every step lives in the module, and only the words are
   here. */

export type TourStep = {
  id: string;
  title: string;
  body: string;
  /** GUI page id this step is about, or '' */
  page: string;
  /** project tab id, or '' */
  tab: string;
  /** the terminal UI key that reaches the same thing, or '' */
  key: string;
  /** manual page, without the extension, or '' */
  docs: string;
  /** the manual URL, or '' */
  docsUrl: string;
};
"""


def _steps(which):
    return [{'id': s['id'], 'title': s['title'], 'body': s['body'],
             'page': s['page'], 'tab': s['tab'], 'key': s['key'],
             'docs': s['docs'], 'docsUrl': T.docs_url(s)}
            for s in T.steps(which)]


def render():
    out = [BANNER]
    for name in T.names():
        out.append('export const TOUR_%s: TourStep[] = %s;\n'
                   % (name.upper(), json.dumps(_steps(name), indent=2)))
    out.append('export const DOCS_BASE = %s;\n' % json.dumps(T.DOCS_BASE))
    return '\n'.join(out)


def main(argv):
    body = render()
    check = '--check' in argv
    have = io.open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
    if have == body:
        print('www/lib/tour.ts is current')
        return 0
    if check:
        print('www/lib/tour.ts is STALE — run: py -3 tools/gen_tour.py')
        return 1
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(body)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
