"""Generate the V1 client's token and presentation files (p16-design-gate D9).

    py tools/gen_ui.py            write them
    py tools/gen_ui.py --check    fail when a generated file is stale, a state
                                  of any machine in archeus/core/domain/states.py
                                  has no presentation class, or a class is
                                  incomplete

Sources: clients/app/tokens/{tokens,presentation,navigation,invalidation}.json.
Outputs for the SPA: src/styles/tokens.css, src/state/tokens.ts,
src/state/presentation.ts, src/nav/table.ts, src/data/rules.ts. Outputs for the
TUI (p17-design-gate A1, A7): archeus/cli/tui/_tables.py and
archeus/cli/tui/tokens.py, because the JSON is not in the wheel. One table,
everything derived — the cluster-spec pattern (tools/gen_cluster_spec.py)
applied to the V1 clients.
"""

import json
import os
import pprint
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
APP = os.path.join(ROOT, 'clients', 'app')
TOKENS = os.path.join(APP, 'tokens', 'tokens.json')
PRESENTATION = os.path.join(APP, 'tokens', 'presentation.json')
CSS_OUT = os.path.join(APP, 'src', 'styles', 'tokens.css')
TOKENS_TS = os.path.join(APP, 'src', 'state', 'tokens.ts')
PRES_TS = os.path.join(APP, 'src', 'state', 'presentation.ts')
NAVIGATION = os.path.join(APP, 'tokens', 'navigation.json')
INVALIDATION = os.path.join(APP, 'tokens', 'invalidation.json')
NAV_TS = os.path.join(APP, 'src', 'nav', 'table.ts')
RULES_TS = os.path.join(APP, 'src', 'data', 'rules.ts')
TUI = os.path.join(ROOT, 'archeus', 'cli', 'tui')
TABLES_PY = os.path.join(TUI, '_tables.py')
TOKENS_PY = os.path.join(TUI, 'tokens.py')
PY_HEAD = '# Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit.\n'
#: keys the TUI keeps for itself everywhere (p17-design-gate §3): no tab may take one
TUI_RESERVED = ('q', '?', ':')
HEAD = '/* Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit. */\n'


def load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def _var(role):
    return '--' + role.replace('.', '-')


def render_css(t):
    out = [HEAD, ':root {']
    for i, v in enumerate(t['space']):
        out.append('  --space-%d: %dpx;' % (i, v))
    for k, v in t['radius'].items():
        out.append('  --radius-%s: %dpx;' % (k, v))
    for k, v in t['motion'].items():
        out.append('  --dur-%s: %dms;' % (k, v))
    out.append('  --ease: %s;' % t['easing'])
    for k, v in t['layout'].items():
        out.append('  --%s: %s;' % (k.replace('_', '-'), '%dch' % v if k.endswith('_ch')
                                      else '%dpx' % v))
    for k, v in t['targets'].items():
        out.append('  --target-%s: %dpx;' % (k, v))
    out.append('  --font: %s;' % t['type']['family'])
    out.append('  --font-mono: %s;' % t['type']['mono'])
    for k, (size, line) in t['type']['desktop'].items():
        out.append('  --type-%s: %.4frem/%.4frem var(--font);' % (k, size / 16, line / 16))
    out.append('  color-scheme: dark light;')
    for role, hexv in t['themes']['dark'].items():
        out.append('  %s: %s;' % (_var(role), hexv))
    out.append('}')
    out.append('@media (prefers-color-scheme: light) {\n  :root {')
    for role, hexv in t['themes']['light'].items():
        out.append('    %s: %s;' % (_var(role), hexv))
    out.append('  }\n}')
    out.append('@media (prefers-contrast: more) {\n  :root {')
    for role, src in t['high_contrast'].items():
        if role.startswith('$'):
            continue
        out.append('    %s: var(%s);' % (_var(role), _var(src)))
    out.append('    --hairline: 2px;\n  }\n}')
    out.append('@media (max-width: %dpx) {\n  :root {' % (t['breakpoints']['tablet'] - 1))
    for k, (size, line) in t['type']['phone'].items():
        out.append('    --type-%s: %.4frem/%.4frem var(--font);' % (k, size / 16, line / 16))
    out.append('  }\n}')
    return '\n'.join(out) + '\n'


def render_tokens_ts(t):
    return (HEAD + 'export const MOTION = %s as const;\nexport const EASING = %s;\n'
            'export const BREAKPOINTS = %s as const;\nexport const TARGETS = %s as const;\n'
            % (json.dumps(t['motion']), json.dumps(t['easing']), json.dumps(t['breakpoints']),
               json.dumps(t['targets'])))


def _label(state):
    return state.replace('_', ' ').capitalize()


def problems(p, t):
    """Everything wrong with the presentation table against the domain."""
    from archeus.core.domain import states
    bad = []
    roles = set(t['themes']['dark']) | {'text-2', 'text-3'}
    for name, c in p['classes'].items():
        for k in ('glyph', 'ascii', 'role', 'name'):
            if not c.get(k):
                bad.append('class %s has no %s' % (name, k))
        if c.get('role') not in roles:
            bad.append('class %s names unknown role %r' % (name, c.get('role')))
    machines = sorted({row[0] for row in states.TABLE})
    for m in machines:
        have = p['machines'].get(m)
        if have is None:
            bad.append('machine %s has no presentation' % m)
            continue
        want = set(states.states(m))
        for s in sorted(want - set(have)):
            bad.append('%s.%s has no presentation class' % (m, s))
        for s in sorted(set(have) - want):
            bad.append('%s.%s is not a state of the machine' % (m, s))
        for s, cls in have.items():
            if cls not in p['classes']:
                bad.append('%s.%s names unknown class %r' % (m, s, cls))
    for m in sorted(set(p['machines']) - set(machines)):
        bad.append('machine %s is not in states.py' % m)
    # the ASCII fallback tells apart exactly what the glyphs tell apart
    by_glyph = {}
    for c in p['classes'].values():
        by_glyph.setdefault(c.get('glyph'), set()).add(c.get('ascii'))
    for g, a in sorted(by_glyph.items()):
        if len(a) != 1:
            bad.append('glyph %s has more than one ASCII glyph: %s' % (g, sorted(a)))
    used = [a for v in by_glyph.values() for a in v]
    for a in sorted({a for a in used if used.count(a) > 1}):
        bad.append('ASCII glyph %r stands for two glyphs' % a)
    return bad


def nav_problems(n):
    """Everything wrong with the navigation table."""
    bad = []
    d = n['destinations']
    for col in ('id', 'key', 'tui'):
        vals = [x[col] for x in d]
        if len(set(vals)) != len(vals):
            bad.append('two destinations share a %s' % col)
    taken = set(TUI_RESERVED) | {x['tui'] for x in d}
    for kind, tabs in n['inspector_tabs'].items():
        missing = [tab for tab in tabs if tab not in n['tabs']]
        if missing:
            bad.append('%s tabs %s have no entry in tabs' % (kind, missing))
            continue
        keys = [n['tabs'][tab]['key'] for tab in tabs]
        if len(set(keys)) != len(keys):
            bad.append('two %s tabs share a key' % kind)
        for k in sorted(set(keys) & taken):
            bad.append('%s tab key %r is taken by the TUI or a destination' % (kind, k))
    return bad


def triggers():
    """Per machine and state, the triggers the P1 table declares from it — what a
    button may be OFFERED for. Legality stays Core's: this only avoids offering
    a move the table does not have."""
    from archeus.core.domain import states
    out = {}
    for m, frm, _to, trig, _g in states.TABLE:
        if frm != '[*]' and trig:
            out.setdefault(m, {}).setdefault(frm, set()).add(trig)
    return {m: {s: sorted(t) for s, t in sorted(v.items())} for m, v in sorted(out.items())}


def render_presentation_ts(p):
    labels = {m: {s: p.get('labels', {}).get(m, {}).get(s) or _label(s) for s in table}
              for m, table in sorted(p['machines'].items())}
    machines = {m: dict(sorted(table.items())) for m, table in sorted(p['machines'].items())}
    return (HEAD +
            'export interface PresentationClass { glyph: string; ascii: string; role: string; name: string }\n'
            'export const CLASSES: Record<string, PresentationClass> = %s;\n'
            'export const PRESENTATION: Record<string, Record<string, string>> = %s;\n'
            'export const LABELS: Record<string, Record<string, string>> = %s;\n'
            '/** Per machine and state, the triggers states.py declares from it. */\n'
            'export const TRIGGERS: Record<string, Record<string, string[]>> = %s;\n'
            % (json.dumps(p['classes'], ensure_ascii=False, indent=2),
               json.dumps(machines, indent=2), json.dumps(labels, ensure_ascii=False, indent=2),
               json.dumps(triggers(), indent=2)))


def render_nav_ts(n):
    return (HEAD
            + 'export interface Destination {\n'
            + "  id: 'now' | 'work' | 'world' | 'attention' | 'control';\n"
            + '  label: string;\n'
            + '  /** keyboard shortcut with Ctrl (Windows/Linux) or Cmd (macOS) */\n'
            + '  key: string;\n'
            + '  /** the TUI key (p17-design-gate §3) */\n'
            + '  tui: string;\n'
            + '  /** on a phone: a bottom tab, or the header menu */\n'
            + "  phone: 'tab' | 'menu';\n"
            + '  blurb: string;\n'
            + '}\n\n'
            + 'export const DESTINATIONS: Destination[] = %s;\n\n'
            % json.dumps(n['destinations'], ensure_ascii=False, indent=2)
            + 'export const CONTROL_SECTIONS = %s as const;\n\n'
            % json.dumps(n['control_sections'], indent=2)
            + '/** The inspector tabs per object kind, in their fixed order (§6.1). */\n'
            + 'export const INSPECTOR_TABS: Record<string, string[]> = %s;\n\n'
            % json.dumps(n['inspector_tabs'], indent=2)
            + 'export const TAB_LABEL: Record<string, string> = %s;\n'
            % json.dumps({k: v['label'] for k, v in n['tabs'].items()}, indent=2))


def render_rules_ts(i):
    return (HEAD + '/** Per subject kind, the read paths it can change (invalidation.json). */\n'
            + 'export const RULES: Record<string, string[]> = %s;\n'
            % json.dumps(i['rules'], indent=2))


def _py(v):
    return pprint.pformat(v, width=99, sort_dicts=False)


def render_tables_py(p, n, i):
    labels = {m: {s: p.get('labels', {}).get(m, {}).get(s) or _label(s) for s in table}
              for m, table in sorted(p['machines'].items())}
    machines = {m: dict(sorted(table.items())) for m, table in sorted(p['machines'].items())}
    parts = [PY_HEAD, '"""The TUI\'s copy of the V1 client tables (p17-design-gate A1):\n'
             'navigation, presentation, triggers and invalidation, from the JSON the SPA\n'
             'reads."""\n']
    for name, value in (('DESTINATIONS', n['destinations']),
                        ('CONTROL_SECTIONS', n['control_sections']),
                        ('INSPECTOR_TABS', n['inspector_tabs']), ('TABS', n['tabs']),
                        ('CLASSES', p['classes']), ('PRESENTATION', machines),
                        ('LABELS', labels), ('TRIGGERS', triggers()), ('RULES', i['rules'])):
        parts.append('\n%s = %s\n' % (name, _py(value)))
    return ''.join(parts)


def render_tokens_py(t):
    """Each foreground role as the nearest non-system ANSI-256 colour (design
    system §15: never 0-15, as the legacy themes do)."""
    from claude_sessions.themes import hex_to_x256
    skip = ('bg', 'surface-1', 'surface-2', 'surface-3', 'on-primary')
    colours = {name: {role: hex_to_x256(h) for role, h in theme.items() if role not in skip}
               for name, theme in t['themes'].items()}
    return (PY_HEAD + '"""The token table as ANSI-256 colours per theme (p17-design-gate A7)."""\n'
            + '\nCOLOURS = %s\n' % _py(colours))


def outputs():
    t, p = load(TOKENS), load(PRESENTATION)
    n, i = load(NAVIGATION), load(INVALIDATION)
    return {CSS_OUT: render_css(t), TOKENS_TS: render_tokens_ts(t),
            PRES_TS: render_presentation_ts(p), NAV_TS: render_nav_ts(n),
            RULES_TS: render_rules_ts(i), TABLES_PY: render_tables_py(p, n, i),
            TOKENS_PY: render_tokens_py(t)}, problems(p, t) + nav_problems(n)


def main(argv):
    files, bad = outputs()
    if bad:
        print('\n'.join(bad), file=sys.stderr)
        return 1
    stale = []
    for path, text in files.items():
        cur = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if '--check' in argv:
            if cur != text:
                stale.append(os.path.relpath(path, ROOT))
        elif cur != text:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print('wrote %s' % os.path.relpath(path, ROOT))
    if stale:
        print('stale (run py tools/gen_ui.py): %s' % ', '.join(stale), file=sys.stderr)
        return 1
    if '--check' in argv:
        print('the generated UI files are current and every state has a presentation')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
