"""Regenerate docs/api.md from the live route tables.

`docs/gui-audit.md` was a hand-written route catalogue that had drifted to
listing seventeen routes which do not exist, alongside a design-issue list
whose items had since been fixed. A hand-maintained copy of something the code
already states is a copy that will be wrong.

    py -3 tools/gen_api_docs.py            # rewrite docs/api.md
    py -3 tools/gen_api_docs.py --check    # exit 1 if it is out of date
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from claude_sessions import gui, gui_api          # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'docs', 'api.md')

HEADER = """# archeus GUI API

Generated by `tools/gen_api_docs.py` from the route tables in `gui_api.py` and
`gui.py` — do not edit by hand. `tests/test_parity_gate.py` fails when this
file is out of date.

Every route is served from loopback and guarded by `gui._guard()`: an
allowlisted `Host`, no browser fetch metadata, and a per-run token in
`X-Archeus`. Parameters named `enc`, `sid` and `cfgdir` are validated before
a handler sees them; a missing or malformed one is a 400.

"""


def _doc(fn):
    d = (fn.__doc__ or '').strip().splitlines()
    return d[0].strip() if d else ''


def render():
    parts = [HEADER]
    for title, table, local in (
            ('GET', gui_api.GET_ROUTES, gui._LOCAL_GET),
            ('POST', gui_api.POST_ROUTES, gui._LOCAL_POST)):
        merged = dict(table)
        merged.update(local)
        parts.append('## %s\n' % title)
        parts.append('| Route | Handler | What it does |')
        parts.append('|---|---|---|')
        for path in sorted(merged):
            fn = merged[path]
            parts.append('| `%s` | `%s` | %s |'
                         % (path, fn.__name__, _doc(fn) or '—'))
        parts.append('')
    parts.append('## Job routes\n')
    parts.append('These are matched by prefix rather than by table lookup.\n')
    parts.append('| Route | What it does |')
    parts.append('|---|---|')
    parts.append('| `GET /api/job/<id>` | Poll a job: status, messages, gate |')
    parts.append('| `POST /api/job/<id>/decide` | Answer an approval gate |')
    parts.append('| `POST /api/job/<id>/cancel` | Cancel a running job |')
    parts.append('')
    return '\n'.join(parts)


def main(argv):
    text = render()
    if '--check' in argv:
        try:
            cur = open(OUT, encoding='utf-8').read()
        except OSError:
            cur = ''
        if cur.replace('\r\n', '\n') != text:
            print('docs/api.md is out of date — run tools/gen_api_docs.py')
            return 1
        print('docs/api.md is current')
        return 0
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('wrote', OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
