"""Regenerate the front-end copies of `claude_sessions/cluster_spec.py`.

Three renderers draw the same cluster — `stage.js`, `www/.../scene.ts` and
`connections.py` — and the user's requirement is that all three represent the
SAME reference rather than three approximations of it. Python can be imported
by one of the three; the other two get a generated copy, and a test fails when
either is stale.

    py -3 tools/gen_cluster_spec.py            # rewrite both
    py -3 tools/gen_cluster_spec.py --check    # exit 1 if either is out of date

Same shape as `tools/gen_api_docs.py`, for the same reason it exists.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from claude_sessions import cluster_spec as CS          # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JS_OUT = os.path.join(ROOT, 'claude_sessions', 'web', 'cluster-spec.js')
TS_OUT = os.path.join(ROOT, 'www', 'lib', 'cluster-spec.ts')

BANNER = """/* GENERATED by tools/gen_cluster_spec.py from claude_sessions/cluster_spec.py.
   Do not edit — the next run overwrites it, and tests/test_cluster_parity.py
   fails while it is stale.

   Every number the cluster and the conduit are made of, so the three renderers
   that draw them cannot drift apart. The reasoning for each one lives in the
   Python module and in notes/cluster-spec.md; only the values are here. */
"""


def _value(v):
    """Python literal -> JSON, with dict keys stringified for JS/TS."""
    if isinstance(v, dict):
        return {str(k): _value(x) for k, x in v.items()}
    if isinstance(v, (tuple, list)):
        return [_value(x) for x in v]
    return v


def payload():
    return {k: _value(getattr(CS, k)) for k in CS.EXPORTED}


def _body():
    d = payload()
    return '\n'.join(
        '  %s: %s,' % (k, json.dumps(d[k], separators=(', ', ': ')))
        for k in CS.EXPORTED)


def render_js():
    return '%s\nconst CLUSTER = {\n%s\n};\n' % (BANNER, _body())


def render_ts():
    return ('%s\nexport const CLUSTER = {\n%s\n} as const;\n\nexport type '
            'ClusterSpec = typeof CLUSTER;\n' % (BANNER, _body()))


TARGETS = ((JS_OUT, render_js), (TS_OUT, render_ts))


def main(argv):
    bad = 0
    for path, render in TARGETS:
        text = render()
        if '--check' in argv:
            try:
                cur = open(path, encoding='utf-8').read()
            except OSError:
                cur = ''
            if cur.replace('\r\n', '\n') != text:
                print(os.path.relpath(path, ROOT),
                      'is out of date — run tools/gen_cluster_spec.py')
                bad = 1
            continue
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print('wrote', os.path.relpath(path, ROOT))
    if '--check' in argv and not bad:
        print('cluster spec copies are current')
    return bad


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
