"""Regenerate every API artefact from the live route tables.

`docs/gui-audit.md` was a hand-written route catalogue that had drifted to
listing seventeen routes which do not exist, alongside a design-issue list
whose items had since been fixed. A hand-maintained copy of something the code
already states is a copy that will be wrong.

    docs/api.md                             the legacy GUI API (gui_api.py, gui.py)
    docs/architecture/api-reference.md      the V1 API (archeus/api/routes.py)
    clients/app/src/api/generated.ts        the V1 SPA's typed client (the same table)

    py -3 tools/gen_api_docs.py            # rewrite all three
    py -3 tools/gen_api_docs.py --check    # exit 1 if any is out of date

Output is deterministic (table order, sorted types, no timestamps), so the
check is a byte comparison and needs no Node.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

OUT = os.path.join(ROOT, 'docs', 'api.md')
V1_REFERENCE = os.path.join(ROOT, 'docs', 'architecture', 'api-reference.md')
V1_CLIENT = os.path.join(ROOT, 'clients', 'app', 'src', 'api', 'generated.ts')

#: The front matter has to be generated too: without it this page falls back to
#: `site_description`, which is 262 characters of pitch and describes the whole
#: product rather than this page. It was the one page in the manual with no
#: description of its own, which `tools/check_site_seo.py` reports as a page
#: whose search snippet is a duplicate of every other page's.
HEADER = """---
description: >-
  Every route of the archeus local HTTP API — the loopback server the desktop
  GUI is built on, its guard, its parameters and its JSON shapes.
---

# archeus GUI API

Generated by `tools/gen_api_docs.py` from the route tables in `gui_api.py` and
`gui.py` — do not edit by hand. `tests/test_parity_gate.py` fails when this
file is out of date.

Every route is served from loopback and guarded by `gui._guard()`: an
allowlisted `Host`, no browser fetch metadata, and a per-run token in
`X-Archeus`. Parameters named `enc`, `sid` and `cfgdir` are validated before
a handler sees them; a missing or malformed one is a 400.

"""


def _doc(fn):
    d = (fn.__doc__ or '').strip().splitlines()
    return d[0].strip() if d else ''


def render():
    from claude_sessions import gui, gui_api      # the legacy tables, only when rendered
    parts = [HEADER]
    for title, table, local in (
            ('GET', gui_api.GET_ROUTES, gui._LOCAL_GET),
            ('POST', gui_api.POST_ROUTES, gui._LOCAL_POST)):
        merged = {**table, **local}
        parts.append('## %s\n' % title)
        parts.append('| Route | Handler | What it does |')
        parts.append('|---|---|---|')
        for path in sorted(merged):
            fn = merged[path]
            parts.append('| `%s` | `%s` | %s |'
                         % (path, fn.__name__, _doc(fn) or '—'))
        parts.append('')
    parts.append('## Job routes\n')
    parts.append('These are matched by prefix rather than by table lookup.\n')
    parts.append('| Route | What it does |')
    parts.append('|---|---|')
    parts.append('| `GET /api/job/<id>` | Poll a job: status, messages, gate |')
    parts.append('| `POST /api/job/<id>/decide` | Answer an approval gate |')
    parts.append('| `POST /api/job/<id>/cancel` | Cancel a running job |')
    parts.append('')
    return '\n'.join(parts)


# ── V1 (p3.5b design gate §5.1, §9, A11) ──

def _v1():
    from archeus.api import auth, routes, schemas
    from archeus.core import engine
    from archeus.core.domain import states
    return auth, routes, schemas, engine, states


def _pascal(name):
    return ''.join(w.capitalize() for w in name.split('_'))


def _camel(name):
    p = _pascal(name)
    return p[0].lower() + p[1:]


def _ts(schema, indent):
    if 'ref' in schema:
        t = schema['ref']
    elif schema['type'] == 'string':
        t = ' | '.join("'%s'" % v for v in schema['enum']) if 'enum' in schema else 'string'
    elif schema['type'] == 'integer':
        t = 'number'
    elif schema['type'] == 'boolean':
        t = 'boolean'
    elif schema['type'] == 'array':
        item = _ts(schema['items'], indent)
        t = ('Array<%s>' % item) if '|' in item else item + '[]'
    elif 'properties' not in schema:
        t = 'Record<string, unknown>'
    else:
        t = _ts_object(schema, indent)
    return t + (' | null' if schema.get('nullable') else '')


def _ts_object(schema, indent):
    """`{ … }` with one member per line, closed at *indent* minus one level."""
    inner = indent + '  '
    lines = ['{']
    for name, sub in schema['properties'].items():
        opt = '' if name in schema.get('required', ()) else '?'
        lines.append('%s%s%s: %s;' % (indent, name, opt, _ts(sub, inner)))
    if schema.get('open'):
        lines.append('%s[field: string]: unknown;' % indent)
    lines.append(indent[:-2] + '}')
    return '\n'.join(lines)


def _request_name(route):
    return _pascal(route.handler.__name__) + 'Request'


def _api_routes(routes):
    return [r for r in routes.ROUTES if r.path.startswith('/v1/')]


QUERY_TYPES = {'state': "Mission['state']", 'after': 'number', 'limit': 'number'}


def render_v1_client():
    auth, routes, schemas, engine, states = _v1()
    q = "'%s'"
    out = ['// Generated by tools/gen_api_docs.py from archeus/api/routes.py and',
           '// archeus/api/schemas.py. Do not edit: the Python check fails when it is stale.',
           '',
           'export const MISSION_STATES = [%s] as const;'
           % ', '.join(q % s for s in states.states('mission')),
           '/** States Core has nothing to do in: ended, or waiting for a human. */',
           'export const SETTLED: readonly string[] = [%s];'
           % ', '.join(q % s for s in engine.SETTLED),
           'export const SCOPES = [%s] as const;' % ', '.join(q % s for s in auth.SCOPES),
           'export const STREAM_PATH = %s;' % (q % routes.STREAM), '']
    for name in sorted(schemas.TYPES):
        out += ['export interface %s %s' % (name, _ts_object(schemas.TYPES[name], '  ')), '']
    for r in _api_routes(routes):
        if r.request_schema is not None:
            out += ['export interface %s %s' % (_request_name(r),
                                                _ts_object(r.request_schema, '  ')), '']
    out += ["export type Method = 'GET' | 'POST';",
            'export type Send = <T>(method: Method, path: string, body?: unknown) => '
            'Promise<T>;',
            '',
            'function qs(q: Record<string, string | number | undefined>): string {',
            '  const p = Object.entries(q)',
            '    .filter(([, v]) => v !== undefined)',
            '    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);',
            "  return p.length ? '?' + p.join('&') : '';",
            '}',
            '',
            '/** One function per route of the table; the stream is read at STREAM_PATH. */',
            'export const api = {']
    for r in _api_routes(routes):
        if r.path == routes.STREAM:
            continue
        params, path = ['send: Send'], q % r.path
        if '{id}' in r.path:
            params.append('id: string')
            head, tail = r.path.split('{id}')
            path = '%s + encodeURIComponent(id)%s' % (q % head, (' + ' + q % tail) if tail else '')
        query = routes.QUERY.get(r.path) if r.method == 'GET' else None
        if query:
            params.append('query: { %s } = {}' % '; '.join(
                '%s?: %s' % (n, QUERY_TYPES[n]) for n in query))
            path += ' + qs(query)'
        body = ''
        if r.request_schema is not None:
            params.append('body: %s' % _request_name(r))
            body = ', body'
        out.append('  %s: (%s) =>\n    send<%s>(%s, %s%s),' % (
            _camel(r.handler.__name__), ', '.join(params), r.response_schema,
            q % r.method, path, body))
    out += ['};', '']
    return '\n'.join(out)


V1_HEADER = """# Archeus V1 API reference

Generated by `tools/gen_api_docs.py` from `archeus/api/routes.py` and
`archeus/api/schemas.py` — do not edit by hand; `tests/v1/contract/test_api_generated.py`
fails when it is out of date. The design is `p3.5b-design-gate.md`: §4 the request
pipeline, §5.5 the error table, §6 the event stream.

One origin, `http://127.0.0.1:7337`, loopback only. Every request is checked in this
order, and a refused one writes nothing: `Host` is exactly `127.0.0.1:7337`; fetch metadata
and `Origin` are same-origin; no `token` or `access_token` in the query; a body of at most
1 MiB; a known route and method; a live device token as `Authorization: Bearer`; the route's
scope; a JSON object body carrying `idempotency_key` on every command except `launch/*`.

A scope belongs to the credential, not to what it touches: whether a principal may fire a
given trigger on a given subject is decided in the application layer (P9), never here.
"""


def render_v1_reference():
    auth, routes, schemas, _engine, _states = _v1()
    out = [V1_HEADER, '## Routes', '',
           '| Method | Path | Scope | Idempotency key | Query | Request | Response |',
           '|---|---|---|---|---|---|---|']
    for r in routes.ROUTES:
        query = ', '.join('`%s`' % n for n in (routes.QUERY.get(r.path, ())
                                              if r.method == 'GET' else ())) or '—'
        req = ('`%s`' % _request_name(r)) if r.request_schema is not None else '—'
        resp = ('`%s`' % r.response_schema) if r.response_schema else 'the built SPA'
        if r.path == routes.STREAM:
            resp = 'SSE: `id`, `event` and a `StreamFrame` per event'
        out.append('| %s | `%s` | %s | %s | %s | %s | %s |' % (
            r.method, r.path, r.scope or 'none', r.idempotent or '—', query, req, resp))
    out += ['', 'A launch-code device holds `%s`; the local token holds `%s`.'
            % (' '.join(auth.LAUNCH_SCOPES), ' '.join(auth.LOCAL_SCOPES)), '', '## Types', '']
    for name in sorted(schemas.TYPES):
        out += ['### `%s`' % name, '', '```ts',
                'interface %s %s' % (name, _ts_object(schemas.TYPES[name], '  ')), '```', '']
    for r in _api_routes(routes):
        if r.request_schema is not None:
            out += ['### `%s`' % _request_name(r), '', '```ts',
                    'interface %s %s' % (_request_name(r), _ts_object(r.request_schema, '  ')),
                    '```', '']
    return '\n'.join(out)


OUTPUTS = ((OUT, render), (V1_REFERENCE, render_v1_reference), (V1_CLIENT, render_v1_client))


def main(argv):
    stale = []
    for path, fn in OUTPUTS:
        text = fn()
        rel = os.path.relpath(path, ROOT).replace(os.sep, '/')
        if '--check' in argv:
            try:
                cur = open(path, encoding='utf-8').read()
            except OSError:
                cur = ''
            if cur.replace('\r\n', '\n') != text:
                stale.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print('wrote', rel)
    if '--check' in argv:
        for rel in stale:
            print('%s is out of date — run tools/gen_api_docs.py' % rel)
        if not stale:
            print('the API references and the generated client are current')
        return 1 if stale else 0
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
