"""Generate the V1 client's token and presentation files (p16-design-gate D9).

    py tools/gen_ui.py            write them
    py tools/gen_ui.py --check    fail when a generated file is stale, a state
                                  of any machine in archeus/core/domain/states.py
                                  has no presentation class, or a class is
                                  incomplete

Sources: clients/app/tokens/tokens.json and clients/app/tokens/presentation.json.
Outputs: clients/app/src/styles/tokens.css, clients/app/src/state/tokens.ts,
clients/app/src/state/presentation.ts. One table, everything derived — the
cluster-spec pattern (tools/gen_cluster_spec.py) applied to the V1 UI.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
APP = os.path.join(ROOT, 'clients', 'app')
TOKENS = os.path.join(APP, 'tokens', 'tokens.json')
PRESENTATION = os.path.join(APP, 'tokens', 'presentation.json')
CSS_OUT = os.path.join(APP, 'src', 'styles', 'tokens.css')
TOKENS_TS = os.path.join(APP, 'src', 'state', 'tokens.ts')
PRES_TS = os.path.join(APP, 'src', 'state', 'presentation.ts')
HEAD = '/* Generated by tools/gen_ui.py from clients/app/tokens/. Do not edit. */\n'


def load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def _var(role):
    return '--' + role.replace('.', '-')


def render_css(t):
    out = [HEAD, ':root {']
    for i, v in enumerate(t['space']):
        out.append('  --space-%d: %dpx;' % (i, v))
    for k, v in t['radius'].items():
        out.append('  --radius-%s: %dpx;' % (k, v))
    for k, v in t['motion'].items():
        out.append('  --dur-%s: %dms;' % (k, v))
    out.append('  --ease: %s;' % t['easing'])
    for k, v in t['layout'].items():
        out.append('  --%s: %s;' % (k.replace('_', '-'), '%dch' % v if k.endswith('_ch')
                                      else '%dpx' % v))
    for k, v in t['targets'].items():
        out.append('  --target-%s: %dpx;' % (k, v))
    out.append('  --font: %s;' % t['type']['family'])
    out.append('  --font-mono: %s;' % t['type']['mono'])
    for k, (size, line) in t['type']['desktop'].items():
        out.append('  --type-%s: %.4frem/%.4frem var(--font);' % (k, size / 16, line / 16))
    out.append('  color-scheme: dark light;')
    for role, hexv in t['themes']['dark'].items():
        out.append('  %s: %s;' % (_var(role), hexv))
    out.append('}')
    out.append('@media (prefers-color-scheme: light) {\n  :root {')
    for role, hexv in t['themes']['light'].items():
        out.append('    %s: %s;' % (_var(role), hexv))
    out.append('  }\n}')
    out.append('@media (prefers-contrast: more) {\n  :root {')
    for role, src in t['high_contrast'].items():
        if role.startswith('$'):
            continue
        out.append('    %s: var(%s);' % (_var(role), _var(src)))
    out.append('    --hairline: 2px;\n  }\n}')
    out.append('@media (max-width: %dpx) {\n  :root {' % (t['breakpoints']['tablet'] - 1))
    for k, (size, line) in t['type']['phone'].items():
        out.append('    --type-%s: %.4frem/%.4frem var(--font);' % (k, size / 16, line / 16))
    out.append('  }\n}')
    return '\n'.join(out) + '\n'


def render_tokens_ts(t):
    return (HEAD + 'export const MOTION = %s as const;\nexport const EASING = %s;\n'
            'export const BREAKPOINTS = %s as const;\nexport const TARGETS = %s as const;\n'
            % (json.dumps(t['motion']), json.dumps(t['easing']), json.dumps(t['breakpoints']),
               json.dumps(t['targets'])))


def _label(state):
    return state.replace('_', ' ').capitalize()


def problems(p, t):
    """Everything wrong with the presentation table against the domain."""
    from archeus.core.domain import states
    bad = []
    roles = set(t['themes']['dark']) | {'text-2', 'text-3'}
    for name, c in p['classes'].items():
        for k in ('glyph', 'role', 'name'):
            if not c.get(k):
                bad.append('class %s has no %s' % (name, k))
        if c.get('role') not in roles:
            bad.append('class %s names unknown role %r' % (name, c.get('role')))
    machines = sorted({row[0] for row in states.TABLE})
    for m in machines:
        have = p['machines'].get(m)
        if have is None:
            bad.append('machine %s has no presentation' % m)
            continue
        want = set(states.states(m))
        for s in sorted(want - set(have)):
            bad.append('%s.%s has no presentation class' % (m, s))
        for s in sorted(set(have) - want):
            bad.append('%s.%s is not a state of the machine' % (m, s))
        for s, cls in have.items():
            if cls not in p['classes']:
                bad.append('%s.%s names unknown class %r' % (m, s, cls))
    for m in sorted(set(p['machines']) - set(machines)):
        bad.append('machine %s is not in states.py' % m)
    return bad


def triggers():
    """Per machine and state, the triggers the P1 table declares from it — what a
    button may be OFFERED for. Legality stays Core's: this only avoids offering
    a move the table does not have."""
    from archeus.core.domain import states
    out = {}
    for m, frm, _to, trig, _g in states.TABLE:
        if frm != '[*]' and trig:
            out.setdefault(m, {}).setdefault(frm, set()).add(trig)
    return {m: {s: sorted(t) for s, t in sorted(v.items())} for m, v in sorted(out.items())}


def render_presentation_ts(p):
    labels = {m: {s: p.get('labels', {}).get(m, {}).get(s) or _label(s) for s in table}
              for m, table in sorted(p['machines'].items())}
    machines = {m: dict(sorted(table.items())) for m, table in sorted(p['machines'].items())}
    return (HEAD +
            'export interface PresentationClass { glyph: string; role: string; name: string }\n'
            'export const CLASSES: Record<string, PresentationClass> = %s;\n'
            'export const PRESENTATION: Record<string, Record<string, string>> = %s;\n'
            'export const LABELS: Record<string, Record<string, string>> = %s;\n'
            '/** Per machine and state, the triggers states.py declares from it. */\n'
            'export const TRIGGERS: Record<string, Record<string, string[]>> = %s;\n'
            % (json.dumps(p['classes'], ensure_ascii=False, indent=2),
               json.dumps(machines, indent=2), json.dumps(labels, ensure_ascii=False, indent=2),
               json.dumps(triggers(), indent=2)))


def outputs():
    t, p = load(TOKENS), load(PRESENTATION)
    return {CSS_OUT: render_css(t), TOKENS_TS: render_tokens_ts(t),
            PRES_TS: render_presentation_ts(p)}, problems(p, t)


def main(argv):
    files, bad = outputs()
    if bad:
        print('\n'.join(bad), file=sys.stderr)
        return 1
    stale = []
    for path, text in files.items():
        cur = open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if '--check' in argv:
            if cur != text:
                stale.append(os.path.relpath(path, ROOT))
        elif cur != text:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, 'w', encoding='utf-8', newline='\n') as f:
                f.write(text)
            print('wrote %s' % os.path.relpath(path, ROOT))
    if stale:
        print('stale (run py tools/gen_ui.py): %s' % ', '.join(stale), file=sys.stderr)
        return 1
    if '--check' in argv:
        print('the generated UI files are current and every state has a presentation')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
