// Generated by tools/gen_api_docs.py from archeus/api/routes.py and
// archeus/api/schemas.py. Do not edit: the Python check fails when it is stale.

export const MISSION_STATES = ['CREATED', 'UNDERSTANDING', 'CONTEXT_GATHERING', 'BLOCKED', 'REASONING', 'PLANNING', 'APPROVAL_REQUIRED', 'APPROVED', 'CANCELLED', 'EXECUTING', 'VERIFYING', 'PAUSED', 'FAILED', 'REPLANNING', 'RESUMED', 'REVIEWING', 'COMPLETED'] as const;
/** States Core has nothing to do in: ended, or waiting for a human. */
export const SETTLED: readonly string[] = ['COMPLETED', 'CANCELLED', 'FAILED', 'BLOCKED', 'PAUSED', 'APPROVAL_REQUIRED'];
export const SCOPES = ['observe', 'control', 'approve', 'admin'] as const;
export const STREAM_PATH = '/v1/events/stream';

export interface Acked {
  up_to_seq: number;
  changed: boolean;
}

export interface ApiError {
  error: string;
  detail: Record<string, unknown>;
}

export interface Card {
  type: 'mission_proposal' | 'plan' | 'approval' | 'route_explanation' | 'diff' | 'verification' | 'digest' | 'mission' | 'idea' | 'challenge' | 'clarification' | 'knowledge' | 'status';
  ref: Subject;
  [field: string]: unknown;
}

export interface CommandResult {
  id: string;
  state: string;
  version: number;
  changed: boolean;
  seq: number | null;
  transitions: Transition[];
}

export interface ConstraintDeclared {
  knowledge_item: KnowledgeItem;
  changed: boolean;
  stale: string[];
}

export interface ContextBudget {
  limit_tokens: number;
  used_tokens: number;
  levels: Record<string, unknown>;
}

export interface ContextConflict {
  items: string[];
  preferred: string;
  kind: string;
  reason: string;
}

export interface ContextExcluded {
  ref: ContextRef;
  level: 'L0' | 'L1' | 'L2' | 'L3' | 'L4';
  freshness: 'current' | 'stale' | 'superseded';
  reason: string;
}

export interface ContextItem {
  ref: ContextRef;
  level: 'L0' | 'L1' | 'L2' | 'L3' | 'L4';
  store: 'state' | 'knowledge' | 'history';
  type: string;
  source_kind: string;
  source_ref: string;
  observed_at: string | null;
  freshness: 'current' | 'stale';
  relevance: number;
  signals: Record<string, unknown>;
  reason: string;
  tokens: number;
  conflicts_with: string[];
}

export interface ContextPackage {
  id: string;
  version: number;
  created_at: string;
  subject_kind: string;
  subject_id: string;
  as_of_seq: number;
  budget: ContextBudget;
  items: ContextItem[];
  excluded: ContextExcluded[];
  conflicts: ContextConflict[];
  [field: string]: unknown;
}

export interface ContextPreview {
  subject_kind: 'mission' | 'project' | 'message';
  subject_id: string;
  workspace_id: string;
  project_id: string | null;
  as_of_seq: number;
  as_of_at: string | null;
  query: string;
  levels: Array<'L0' | 'L1' | 'L2' | 'L3' | 'L4'>;
  budget: ContextBudget;
  scoring: Record<string, unknown>;
  items: ContextItem[];
  excluded: ContextExcluded[];
  conflicts: ContextConflict[];
  assumptions: string[];
  missing_information: string[];
  [field: string]: unknown;
}

export interface ContextRef {
  kind: string;
  id: string;
  version?: number;
  seq?: number;
  [field: string]: unknown;
}

export interface Created {
  id: string;
  state: string;
  version: number;
  seq: number;
}

export interface Criterion {
  text: string;
  check: 'automatic' | 'human';
  origin?: 'explicit' | 'inferred';
}

export interface Digest {
  from_seq: number;
  up_to_seq: number;
  count: number;
  groups: DigestGroup[];
  truncated: boolean;
}

export interface DigestGroup {
  ref: Subject;
  headline: 'needs_you' | 'drift_found' | 'failed' | 'completed' | 'drift_cleared' | 'progressed';
  count: number;
  first_seq: number;
  last_seq: number;
  project_id: string | null;
  types: string[];
}

export interface Event {
  seq: number;
  id: string;
  type: string;
  at: string;
  actor: {
    kind: string;
    id: string;
  };
  cause_chain: string[];
  subject: Subject;
  scope: Scope;
  visibility: 'user' | 'system';
  payload: Record<string, unknown>;
}

export interface EventPage {
  events: Event[];
}

export interface FeedbackRecorded {
  feedback_id: string;
  promoted: KnowledgeItem | null;
  seq: number;
}

export interface Finding {
  constraint_id: string;
  constraint: string;
  kind: 'doc_matches_code' | 'forbid_dependency' | 'framework_pinned' | 'module_exists' | 'require_layering' | null;
  status: 'violated' | 'satisfied' | 'unchecked';
  reason: string | null;
  violations: string[][];
  violation_count: number;
  [field: string]: unknown;
}

export interface Forgotten {
  dry_run: boolean;
  mode: 'retract' | 'purge';
  changes: Record<string, unknown>[];
  changed: boolean;
}

export interface Health {
  core: {
    pid: number;
    started_at: string;
    version: string;
    schema: number;
    ports: 'stub' | 'real';
  };
  engine: {
    state: 'starting' | 'reconciling' | 'running' | 'idle' | 'failed' | 'stopped';
    observed_seq: number;
    parked: number;
  };
  world: {
    state: 'starting' | 'reconciling' | 'running' | 'idle' | 'failed' | 'stopped';
    pending: number;
  };
  knowledge: Worker;
  intent: Worker;
  plan: Worker;
}

export interface Idea {
  id: string;
  state: 'CAPTURED' | 'COMPLETED' | 'CONCEPT' | 'DISCARDED' | 'EXPLORED' | 'IMPLEMENTING' | 'LEARNED' | 'PARKED' | 'PLANNED' | 'SCHEDULED' | 'UNDERSTOOD' | 'VALIDATED';
  text: string;
  title?: string;
  promoted_mission_id?: string | null;
  [field: string]: unknown;
}

export interface IdeaList {
  ideas: Idea[];
}

export interface Inspection {
  id: string;
  repository_id: string;
  revision: string | null;
  extractor_version: number;
  state: 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  attempts: number;
  failure?: string | null;
  version: number;
  [field: string]: unknown;
}

export interface InspectionList {
  inspections: Inspection[];
}

export interface Intent {
  id: string;
  message_id: string;
  kind: 'control_verb' | 'question' | 'new_work' | 'continue_work' | 'feedback' | 'preference' | 'idea';
  via: 'grammar' | 'brain';
  resolution: 'answered' | 'mission_created' | 'mission_updated' | 'clarification_requested' | 'declined' | null;
  [field: string]: unknown;
}

export interface KnowledgeChanged {
  knowledge_item: KnowledgeItem;
  changed: boolean;
  [field: string]: unknown;
}

export interface KnowledgeDetail {
  id: string;
  state: string;
  chain: string[];
  relations: Record<string, unknown>[];
  [field: string]: unknown;
}

export interface KnowledgeItem {
  id: string;
  type: string;
  title: string;
  state: 'CANDIDATE' | 'CONFIRMED' | 'RETRACTED' | 'SUPERSEDED' | 'EXPIRED';
  constraint?: Record<string, unknown> | null;
  version: number;
  [field: string]: unknown;
}

export interface KnowledgeList {
  knowledge: KnowledgeItem[];
}

export interface LaunchCode {
  code: string;
  expires_in: number;
}

export interface Meeting {
  id: string;
  name: string;
  held_at: string | null;
  project_id: string | null;
  notes_artifact_id?: string | null;
  [field: string]: unknown;
}

export interface MeetingImported {
  meeting: Meeting;
  changed: boolean;
}

export interface Message {
  id: string;
  conversation_id: string;
  author: 'user' | 'archeus' | 'system';
  text: string;
  in_reply_to: string | null;
  cards: Card[];
  links: Record<string, unknown>[];
  intent_id?: string | null;
  [field: string]: unknown;
}

export interface MessageList {
  messages: Message[];
}

export interface MessagePosted {
  message_id: string;
  conversation_id: string;
  seq: number;
}

export interface Mission {
  id: string;
  state: 'APPROVAL_REQUIRED' | 'APPROVED' | 'BLOCKED' | 'CANCELLED' | 'COMPLETED' | 'CONTEXT_GATHERING' | 'CREATED' | 'EXECUTING' | 'FAILED' | 'PAUSED' | 'PLANNING' | 'REASONING' | 'REPLANNING' | 'RESUMED' | 'REVIEWING' | 'UNDERSTANDING' | 'VERIFYING';
  title: string;
  objective: string;
  workspace_id?: string;
  project_id?: string | null;
  version: number;
  created_at: string;
  updated_at: string;
  plan_id?: string | null;
  plan_version?: number | null;
  planning_blocked?: Record<string, unknown> | null;
  [field: string]: unknown;
}

export interface MissionList {
  missions: Mission[];
}

export interface MissionPlan {
  mission_id: string;
  plan: Plan | null;
  versions: PlanVersionRef[];
}

export interface Plan {
  id: string;
  mission_id: string;
  plan_version: number;
  state: 'APPROVED' | 'DRAFT' | 'PROPOSED' | 'REJECTED' | 'SUPERSEDED';
  estimated_cost?: 'low' | 'medium' | 'high' | null;
  supersedes_plan_id?: string | null;
  digest?: string | null;
  tasks: Task[];
  waves: string[][];
  serialised?: Record<string, unknown>[];
  current: boolean;
  current_why: string;
  [field: string]: unknown;
}

export interface PlanVersionRef {
  id: string;
  plan_version: number;
  state: 'APPROVED' | 'DRAFT' | 'PROPOSED' | 'REJECTED' | 'SUPERSEDED';
  supersedes_plan_id: string | null;
  digest: string | null;
}

export interface Project {
  id: string;
  name: string;
  state: 'ACTIVE' | 'ARCHIVED';
  root_paths: string[];
  repositories?: Repository[];
  version: number;
  [field: string]: unknown;
}

export interface ProjectCreated {
  project: Project;
  repositories: Repository[];
}

export interface ProjectList {
  projects: Project[];
}

export interface ProviderTerms {
  id: string;
  headless: 'unknown' | 'permitted' | 'refused';
  rotation: 'unknown' | 'permitted' | 'refused';
  note?: string;
  [field: string]: unknown;
}

export interface ProviderTermsDecided {
  provider_terms: ProviderTerms;
}

export interface ProviderTermsList {
  provider_terms: ProviderTerms[];
}

export interface Redeemed {
  device_id: string;
  token: string;
}

export interface Replied {
  reply_id?: string | null;
  intent_id?: string | null;
  resolution?: string | null;
  [field: string]: unknown;
}

export interface Repository {
  id: string;
  project_id: string;
  path: string;
  kind: 'repo' | 'submodule' | 'worktree';
  architecture_state: 'UNKNOWN' | 'CONSISTENT' | 'DRIFTED' | 'STALE';
  last_revision?: string | null;
  last_inspection_id?: string | null;
  findings?: Finding[];
  version: number;
  [field: string]: unknown;
}

export interface RouteDecision {
  id: string;
  purpose?: string | null;
  decided_by?: string | null;
  selected: string | null;
  model?: string | null;
  candidates: Record<string, unknown>[];
  explanation: string;
  outcome: Record<string, unknown> | null;
  [field: string]: unknown;
}

export interface RouteDecisionList {
  route_decisions: RouteDecision[];
}

export interface Scope {
  workspace: string;
  project: string | null;
}

export interface Status {
  source: 'deterministic';
  as_of_seq: number;
  projects: Record<string, unknown>[];
  missions: Mission[];
  drift: Finding[];
  unchecked: Finding[];
  unknown_project: string[];
}

export interface StreamFrame {
  subject: Subject;
  scope: Scope;
}

export interface Subject {
  kind: string;
  id: string;
}

export interface Task {
  id: string;
  key: string;
  title: string;
  kind: 'code_change' | 'research' | 'document' | 'presentation' | 'inspection' | 'verification' | 'human';
  state: 'AWAITING_APPROVAL' | 'BLOCKED' | 'CANCELLED' | 'FAILED' | 'PAUSED' | 'PENDING' | 'READY' | 'ROUTING' | 'RUNNING' | 'SKIPPED' | 'SUCCEEDED' | 'VERIFYING';
  depends_on: string[];
  acceptance: Record<string, unknown>[];
  [field: string]: unknown;
}

export interface Transition {
  from: string;
  to: string;
  trigger: string;
  seq: number;
}

export interface Version {
  version: string;
  api: string;
}

export interface Worker {
  state: 'starting' | 'reconciling' | 'running' | 'idle' | 'failed' | 'stopped';
  pending: number;
}

export interface CreateMissionRequest {
  title: string;
  objective: string;
  project_id?: string | null;
  success_criteria?: Criterion[];
  idempotency_key: string;
}

export interface PauseMissionRequest {
  idempotency_key: string;
}

export interface ResumeMissionRequest {
  idempotency_key: string;
}

export interface LaunchCodeRequest {
}

export interface LaunchRedeemRequest {
  code: string;
  platform: 'web' | 'desktop';
}

export interface RevokeDeviceRequest {
  idempotency_key: string;
}

export interface CreateProjectRequest {
  name: string;
  root_paths: string[];
  idempotency_key: string;
}

export interface DeclareConstraintRequest {
  statement: string;
  kind?: 'doc_matches_code' | 'forbid_dependency' | 'framework_pinned' | 'module_exists' | 'require_layering' | null;
  spec?: Record<string, unknown> | null;
  idempotency_key: string;
}

export interface AckDigestRequest {
  up_to_seq: number;
}

export interface PreviewContextRequest {
  subject: {
    kind: 'mission' | 'project' | 'message';
    id: string;
  };
  query?: string | null;
  levels?: Array<'L0' | 'L1' | 'L2' | 'L3' | 'L4'> | null;
  limit_tokens?: number | null;
}

export interface ConfirmKnowledgeRequest {
  reason?: string | null;
  expected_version?: number | null;
  idempotency_key: string;
}

export interface RejectKnowledgeRequest {
  reason?: string | null;
  expected_version?: number | null;
  idempotency_key: string;
}

export interface RetractKnowledgeRequest {
  reason?: string | null;
  expected_version?: number | null;
  idempotency_key: string;
}

export interface SupersedeKnowledgeRequest {
  title: string;
  text?: string | null;
  idempotency_key: string;
}

export interface ForgetKnowledgeRequest {
  selector: Record<string, unknown>;
  mode?: 'retract' | 'purge' | null;
  dry_run?: boolean | null;
  idempotency_key: string;
}

export interface RecordFeedbackRequest {
  subject: {
    kind: string;
    id: string;
  };
  signal: 'positive' | 'negative' | 'correction';
  text?: string | null;
  promote?: {
    type: 'PREFERENCE' | 'LESSON';
    title: string;
    text?: string | null;
    supersedes_id?: string | null;
  } | null;
  idempotency_key: string;
}

export interface ImportMeetingRequest {
  path: string;
  project_id?: string | null;
  held_at?: string | null;
  allow_undated?: boolean | null;
  idempotency_key: string;
}

export interface DecideProviderTermsRequest {
  headless: 'unknown' | 'permitted' | 'refused';
  rotation?: 'unknown' | 'permitted' | 'refused' | null;
  note?: string | null;
  idempotency_key: string;
}

export interface PostMessageRequest {
  text: string;
  in_reply_to?: string | null;
  idempotency_key: string;
}

export interface ClarifyIntentRequest {
  choice?: 'proceed' | 'drop' | null;
  text?: string | null;
  idempotency_key: string;
}

export type Method = 'GET' | 'POST';
export type Send = <T>(method: Method, path: string, body?: unknown) => Promise<T>;

function qs(q: Record<string, string | number | undefined>): string {
  const p = Object.entries(q)
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(String(v))}`);
  return p.length ? '?' + p.join('&') : '';
}

/** One function per route of the table; the stream is read at STREAM_PATH. */
export const api = {
  health: (send: Send) =>
    send<Health>('GET', '/v1/health'),
  version: (send: Send) =>
    send<Version>('GET', '/v1/version'),
  listMissions: (send: Send, query: { state?: Mission['state']; project?: string } = {}) =>
    send<MissionList>('GET', '/v1/missions' + qs(query)),
  getMission: (send: Send, id: string) =>
    send<Mission>('GET', '/v1/missions/' + encodeURIComponent(id)),
  getMissionPlan: (send: Send, id: string) =>
    send<MissionPlan>('GET', '/v1/missions/' + encodeURIComponent(id) + '/plan'),
  getPlan: (send: Send, id: string) =>
    send<Plan>('GET', '/v1/plans/' + encodeURIComponent(id)),
  createMission: (send: Send, body: CreateMissionRequest) =>
    send<Created>('POST', '/v1/missions', body),
  pauseMission: (send: Send, id: string, body: PauseMissionRequest) =>
    send<CommandResult>('POST', '/v1/missions/' + encodeURIComponent(id) + '/pause', body),
  resumeMission: (send: Send, id: string, body: ResumeMissionRequest) =>
    send<CommandResult>('POST', '/v1/missions/' + encodeURIComponent(id) + '/resume', body),
  events: (send: Send, query: { after?: number; limit?: number } = {}) =>
    send<EventPage>('GET', '/v1/events' + qs(query)),
  launchCode: (send: Send, body: LaunchCodeRequest) =>
    send<LaunchCode>('POST', '/v1/devices/launch/code', body),
  launchRedeem: (send: Send, body: LaunchRedeemRequest) =>
    send<Redeemed>('POST', '/v1/devices/launch/redeem', body),
  revokeDevice: (send: Send, id: string, body: RevokeDeviceRequest) =>
    send<CommandResult>('POST', '/v1/devices/' + encodeURIComponent(id) + '/revoke', body),
  status: (send: Send, query: { project?: string } = {}) =>
    send<Status>('GET', '/v1/status' + qs(query)),
  listProjects: (send: Send) =>
    send<ProjectList>('GET', '/v1/projects'),
  getProject: (send: Send, id: string) =>
    send<Project>('GET', '/v1/projects/' + encodeURIComponent(id)),
  createProject: (send: Send, body: CreateProjectRequest) =>
    send<ProjectCreated>('POST', '/v1/projects', body),
  declareConstraint: (send: Send, id: string, body: DeclareConstraintRequest) =>
    send<ConstraintDeclared>('POST', '/v1/projects/' + encodeURIComponent(id) + '/constraints', body),
  listInspections: (send: Send, id: string, query: { limit?: number } = {}) =>
    send<InspectionList>('GET', '/v1/repositories/' + encodeURIComponent(id) + '/inspections' + qs(query)),
  digest: (send: Send) =>
    send<Digest>('GET', '/v1/digest'),
  ackDigest: (send: Send, body: AckDigestRequest) =>
    send<Acked>('POST', '/v1/digest/ack', body),
  getContextPackage: (send: Send, id: string) =>
    send<ContextPackage>('GET', '/v1/context/' + encodeURIComponent(id)),
  previewContext: (send: Send, body: PreviewContextRequest) =>
    send<ContextPreview>('POST', '/v1/context/preview', body),
  listKnowledge: (send: Send, query: { project?: string; state?: KnowledgeItem['state']; type?: string } = {}) =>
    send<KnowledgeList>('GET', '/v1/knowledge' + qs(query)),
  getKnowledge: (send: Send, id: string) =>
    send<KnowledgeDetail>('GET', '/v1/knowledge/' + encodeURIComponent(id)),
  confirmKnowledge: (send: Send, id: string, body: ConfirmKnowledgeRequest) =>
    send<KnowledgeChanged>('POST', '/v1/knowledge/' + encodeURIComponent(id) + '/confirm', body),
  rejectKnowledge: (send: Send, id: string, body: RejectKnowledgeRequest) =>
    send<KnowledgeChanged>('POST', '/v1/knowledge/' + encodeURIComponent(id) + '/reject', body),
  retractKnowledge: (send: Send, id: string, body: RetractKnowledgeRequest) =>
    send<KnowledgeChanged>('POST', '/v1/knowledge/' + encodeURIComponent(id) + '/retract', body),
  supersedeKnowledge: (send: Send, id: string, body: SupersedeKnowledgeRequest) =>
    send<KnowledgeChanged>('POST', '/v1/knowledge/' + encodeURIComponent(id) + '/supersede', body),
  forgetKnowledge: (send: Send, body: ForgetKnowledgeRequest) =>
    send<Forgotten>('POST', '/v1/knowledge/forget', body),
  recordFeedback: (send: Send, body: RecordFeedbackRequest) =>
    send<FeedbackRecorded>('POST', '/v1/feedback', body),
  importMeeting: (send: Send, body: ImportMeetingRequest) =>
    send<MeetingImported>('POST', '/v1/meetings/import', body),
  listRouteDecisions: (send: Send, query: { source?: string; purpose?: string } = {}) =>
    send<RouteDecisionList>('GET', '/v1/route-decisions' + qs(query)),
  getRouteDecision: (send: Send, id: string) =>
    send<RouteDecision>('GET', '/v1/route-decisions/' + encodeURIComponent(id)),
  listProviderTerms: (send: Send) =>
    send<ProviderTermsList>('GET', '/v1/provider-terms'),
  decideProviderTerms: (send: Send, id: string, body: DecideProviderTermsRequest) =>
    send<ProviderTermsDecided>('POST', '/v1/provider-terms/' + encodeURIComponent(id), body),
  listMessages: (send: Send, id: string, query: { after?: number } = {}) =>
    send<MessageList>('GET', '/v1/conversations/' + encodeURIComponent(id) + '/messages' + qs(query)),
  postMessage: (send: Send, id: string, body: PostMessageRequest) =>
    send<MessagePosted>('POST', '/v1/conversations/' + encodeURIComponent(id) + '/messages', body),
  getIntent: (send: Send, id: string) =>
    send<Intent>('GET', '/v1/intents/' + encodeURIComponent(id)),
  clarifyIntent: (send: Send, id: string, body: ClarifyIntentRequest) =>
    send<Replied>('POST', '/v1/intents/' + encodeURIComponent(id) + '/clarify', body),
  listIdeas: (send: Send, query: { state?: Mission['state'] } = {}) =>
    send<IdeaList>('GET', '/v1/ideas' + qs(query)),
};
